grafana/tempo-operator

internal/manifests/queryfrontend/query_frontend.go, internal/manifests/queryfrontend/query_frontend_test.go
Signed-off-by: Kevin Earls <kearls@redhat.com>
This fixes #77 and also adds a test case where jaeger-query is enabled
=> Only expose jaeger query ports if jaeger-query is enabled

README.md
Minio is deployed to the 'minio' namespace when following the instructions in the README.
=> Update README: fix minio endpoint

internal/manifests/mutate_test.go
Resolves failing CI https://github.com/os-observability/tempo-operator/actions/runs/3520059269/jobs/5900624988
=> Do not use deprecated Int32Ptr

internal/manifests/manifestutils/naming.go, internal/manifests/memberlist/gossip.go, internal/manifests/memberlist/gossip_test.go, tests/e2e/smoketest-with-jaeger/01-assert.yaml
This is required to support multiple tempo instances in the same namespace.
Instead of updating the label name, it makes the selector of the gossip-ring service more strict to only match pods created by this controller (and with the same instance name). Is there any drawback to this vs. renaming the label per-instance?
Resolves: #71
=> Add common labels (including instance name) to the gossip ring selector

apis/tempo/v1alpha1/microservices_types.go, apis/tempo/v1alpha1/microservices_webhook.go, apis/tempo/v1alpha1/microservices_webhook_test.go, bundle/manifests/tempo-operator.clusterserviceversion.yaml, bundle/manifests/tempo.grafana.com_microservices.yaml, config/crd/bases/tempo.grafana.com_microservices.yaml, config/manifests/bases/tempo-operator.clusterserviceversion.yaml, docs/api.md, internal/manifests/compactor/compactor.go, internal/manifests/compactor/compactor_test.go, internal/manifests/config/build.go, internal/manifests/config/configmap.go, internal/manifests/distributor/distributor.go, internal/manifests/distributor/distributor_test.go, internal/manifests/ingester/ingester.go, internal/manifests/ingester/ingester_test.go, internal/manifests/manifests.go, internal/manifests/manifests_test.go, internal/manifests/manifestutils/labels.go, internal/manifests/memberlist/gossip.go, internal/manifests/naming/naming.go, internal/manifests/naming/naming_test.go, internal/manifests/querier/querier.go, internal/manifests/querier/querier_test.go, internal/manifests/queryfrontend/query_frontend.go, internal/manifests/queryfrontend/query_frontend_test.go, internal/manifests/serviceaccount/serviceaccount.go, internal/manifests/serviceaccount/serviceaccount_test.go, tests/e2e/smoketest-with-jaeger/01-assert.yaml
Use a service account for all components:
* serviceAccount can be specified in the CR
* if specified in the CR, it will get validated in the validator webhook
* if not specified in the CR, the operator creates a default SA
Current (afaics unrelated) issues:
* the PodAntiAffinity rule of the query-frontend pod prevents the deployment from adding a new pod (and terminating the old one) during reconciling if the cluster only has a single node: `Warning  FailedScheduling  22s (x11 over 20m)  default-scheduler  0/1 nodes are available: 1 node(s) didn't match pod anti-affinity rules. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.`
Resolves: #101
=> Use a service account for all components

apis/tempo/v1alpha1/microservices_types.go, apis/tempo/v1alpha1/microservices_webhook.go, apis/tempo/v1alpha1/microservices_webhook_test.go, controllers/tempo/microservices_controller.go
* checks if the secret name is set and refers to an existing secret
* checks if the secret content is empty
* checks if all required fields are set in the secret
* checks if the endpoint is a valid URL
The branch of this PR is based on #124 because it also requires the custom validator.
Resolves: #58
=> Validate storage secret

Makefile, tests/e2e/reconcile/00-install-minio.yaml, tests/e2e/smoketest-with-jaeger/00-install-minio.yaml
Kuttl runs both e2e tests in parallel, and if `kubectl apply -f minio.yaml` is executed simultaneously, it will likely fail with `error when creating "minio.yaml": ... already exists`.
Steps to reproduce race condition:
```
kubectl delete -f minio.yaml
kubectl apply -f minio.yaml & kubectl apply -f minio.yaml
kubectl apply -f minio.yaml ; kubectl apply -f minio.yaml
```
=> Deploy minio before kuttl e2e tests

apis/tempo/v1alpha1/microservices_types.go, controllers/tempo/microservices_controller.go, tests/e2e/reconcile/03-update-storage-secret.yaml, tests/e2e/reconcile/04-check-bucket-name.yaml
The tempo configuration file (ConfigMap) needs to be updated if the content of the storage secret changes.
Resolves: #133
=> Watch storage secret and reconcile on changes

internal/manifests/queryfrontend/query_frontend.go, internal/manifests/queryfrontend/query_frontend_test.go, tests/e2e/smoketest-with-jaeger/01-assert.yaml
The tempo-query pod port names are "jaeger-ui" and "jaeger-metrics", but the service port mappings were prefixed with tempo-query-*.
This change syncs the service port mapping names with the pod port names, and uses intstr.FromString to have descriptive names in the service configuration (and in UIs like the OpenShift Console).
=> Simplify query-frontend service port mappings

controllers/tempo/microservices_controller.go, internal/manifests/compactor/compactor.go, internal/manifests/compactor/compactor_test.go, internal/manifests/config/configmap.go, internal/manifests/config/configmap_test.go, internal/manifests/distributor/distributor.go, internal/manifests/distributor/distributor_test.go, internal/manifests/ingester/ingester.go, internal/manifests/ingester/ingester_test.go, internal/manifests/manifests.go, internal/manifests/manifests_test.go, internal/manifests/manifestutils/annotations.go, internal/manifests/manifestutils/params.go, internal/manifests/querier/querier.go, internal/manifests/querier/querier_test.go, internal/manifests/queryfrontend/query_frontend.go, internal/manifests/queryfrontend/query_frontend_test.go, tests/e2e/reconcile/03-assert.yaml, tests/e2e/reconcile/03-update-storage-secret.yaml, tests/e2e/reconcile/04-check-bucket-name.yaml
This change adds the checksum of the tempo configuration file to the PodTemplateSpec of each Deployment and StatefulSet. If the tempo configuration changes, the checksum will be updated, and the Deployments and StatefulSet will trigger a recreation of the pods.
This is required for tempo to load the new configuration.
Resolves: #137
Note: This PR is based on #154 because of the e2e tests, I'll rebase this PR once #154 is merged.
=> Restart pods when the tempo configuration changes

internal/manifests/compactor/compactor.go, internal/manifests/compactor/compactor_test.go, internal/manifests/distributor/distributor.go, internal/manifests/distributor/distributor_test.go, internal/manifests/ingester/ingester.go, internal/manifests/ingester/ingester_test.go, internal/manifests/manifestutils/constants.go, internal/manifests/manifestutils/securitycontext.go, internal/manifests/querier/querier.go, internal/manifests/querier/querier_test.go, internal/manifests/queryfrontend/query_frontend.go, internal/manifests/queryfrontend/query_frontend_test.go
This resolves permission errors on OpenShift (the user in the container has no permissions to write to /var/tempo inside the container FS) and improves security by preventing writes to the container FS, disallowing privilege escalation and dropping all capabilities.
Ref. https://github.com/grafana/helm-charts/pull/1672
tempo-query filesystem cannot be set to readonly due to https://github.com/grafana/tempo/issues/1621
=> Set SecurityContext and mount /var/tempo in emptyDir volumes

internal/manifests/distributor/distributor.go, internal/manifests/distributor/distributor_test.go, internal/manifests/ingester/ingester.go, internal/manifests/ingester/ingester_test.go, internal/manifests/manifestutils/affinity.go, internal/manifests/querier/querier.go, internal/manifests/querier/querier_test.go, internal/manifests/queryfrontend/query_frontend.go, internal/manifests/queryfrontend/query_frontend_test.go
Using slightly modified best practices from the tempo-distributed helm chart at https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/values.yaml.
In the helm chart
* distributor, query and query-frontend use podAntiAffinity with requiredDuringSchedulingIgnoredDuringExecution so that a pod cannot be scheduled on the same node twice, and preferredDuringSchedulingIgnoredDuringExecution for the failure domain
* ingester uses podAntiAffinity with preferredDuringSchedulingIgnoredDuringExecution so that a pod should not be scheduled on the same node or failure domain twice
* compactor has no podAntiAffinity set
In this PR distributor, query, query-frontend and ingester components get a podAntiAffinity with preferredDuringSchedulingIgnoredDuringExecution so that a pod should …
=> Update PodAntiAffinity for most components

internal/manifests/config/build.go, internal/manifests/config/build_test.go, internal/manifests/config/configmap.go, internal/manifests/config/tempo-config.yaml, internal/manifests/manifestutils/constants.go, tests/e2e/generate/01-assert.yaml, tests/e2e/reconcile/01-assert.yaml, tests/e2e/reconcile/02-assert.yaml, tests/e2e/smoketest-with-jaeger/01-assert.yaml
Upstream tempo updated the default port to 3200, let's also update the default port in the operator.
Resolves: #128
=> Update default tempo HTTP port to 3200

internal/manifests/gateway/gateway-tenants.yaml
=> fix: rbac and rego cm files are mounted into different path

apis/tempo/v1alpha1/microservices_webhook.go, apis/tempo/v1alpha1/microservices_webhook_test.go, controllers/tempo/microservices_controller.go, controllers/tempo/microservices_controller_test.go
This partially reverts https://github.com/os-observability/tempo-operator/pull/167 and brings back validation of the storage secret in the validation webhook.
However, a missing secret does not fail the validation. Instead, the cluster will be in a degraded state until the storage secret is set.
This is helpful in case manifests get applied out of order, i.e. the Tempo CR gets created before the storage secret.
I also fixed an error where the condition message didn't get updated when an invalid secret got updated (e.g. a secret with a missing endpoint got updated to add an invalid endpoint).
cc @pavolloffay
=> Validate storage secret in webhook if it exists

apis/config/v1alpha1/projectconfig_types.go, apis/tempo/v1alpha1/microservices_types.go, bundle/manifests/tempo-operator.clusterserviceversion.yaml, cmd/root.go, config/rbac/role.yaml, controllers/tempo/microservices_controller.go, go.mod, go.sum, internal/handlers/gateway/basedomain.go, internal/manifests/gateway/configs.go, internal/manifests/gateway/configs_test.go, internal/manifests/gateway/gateway-tenants.yaml, internal/manifests/gateway/gateway.go
Resolves #244 
Tested on CRC with 
```yaml
kubectl apply -f - <<EOF
apiVersion: tempo.grafana.com/v1alpha1
kind: Microservices
metadata:
name: simplest
spec:
storage:
secret: minio-test
storageSize: 1Gi
resources:
total:
limits:
memory: 2Gi
cpu: 2000m
tenants:
mode: openshift
authentication:
- tenantName: dev
tenantId: "1610b0c3-c509-4592-a256-a1871353dbfa"
- tenantName: production
tenantId: "1610b0c3-c509-4592-a256-a1871353dbfb"
authorization:
roleBindings:
- name: read-write
roles:
- read-write-traces
subjects:
- kind: user
name: system:serviceaccount:ploffay:dev-collector
- kind: user
name: system:serviceaccount:ploffay:production-collector
- kind: user
name: kubeadmin
roles:
- name: read-write-traces
permissions:
- read
- write
resources: 
- traces
tenants:
- dev
- production …
```
=> Set OCP oauth redirect URL dynamically

Dockerfile
make build runs the generate task, which depends on controller-gen, crdoc and kustomize.
=> Cache tool dependencies in docker layer

internal/manifests/gateway/configs_test.go, internal/manifests/gateway/gateway-tenants.yaml
**Testing**
```
apiVersion: tempo.grafana.com/v1alpha1
kind: Microservices
metadata:
name: foo
spec:
images:
tempo: docker.io/grafana/tempo:1.5.0
tempoQuery: docker.io/grafana/tempo-query:main-0c1eb27
tempoGateway: ghcr.io/frzifus/obs-api:print-tenant
template:
queryFrontend:
jaegerQuery:
enabled: true
gateway:
enabled: true
storage:
secret: minio-test
storageSize: 200M
tenants:
mode: static
authentication:
- tenantName: test-oidc
tenantId: test-oidc
oidc:
secret:
name: test-oidc
issuerURL: https://dex.klimlive.de/dex
authorization:
roleBindings:
- name: test-oidc
roles:
- read-write
subjects:
- kind: user
name: user
roles:
- name: read-write
permissions:
- read
- write
resources:
- logs
- metrics
- traces
tenants:
- test-oidc
```
---
```bash
go run main.go generate --cr install.yaml > …
```
=> fix: gateway crashloop on k8s

tests/e2e/smoketest-with-jaeger/03-run-check-services.yaml
On OpenShift, we don't have permission to write to files in the container fs.
=> Fix e2e smoketest on OpenShift

cmd/root.go
Current operator log format:
```
1.6777675603445392e+09	INFO	Resource has been unchanged	[...]
```
New format:
```
2023-03-03T14:12:09.668Z	INFO	Resource has been unchanged	[...]
```
Resolves: #269
=> Use iso8601 format for logging timestamps

apis/tempo/v1alpha1/tempostack_webhook.go, bundle/manifests/tempo-operator.clusterserviceversion.yaml, config/webhook/manifests.yaml
(I assume `kb.io` came from the kubebuilder template)
=> Update webhook name, replace kb.io with tempo.grafana.com

apis/config/v1alpha1/projectconfig_types.go, apis/config/v1alpha1/projectconfig_types_test.go, cmd/root.go, cmd/root_test.go, cmd/testdata/tlsprofile_invalid.yaml, cmd/testdata/tlsprofile_old.yaml
Resolves: #266
We don't need a dedicated Default() function, as we can just set default values in `root.go` when we create an instance of `ProjectConfig`
=> Set default TLSProfile and validate ProjectConfig

controllers/tempo/tempostack_controller.go, controllers/tempo/tempostack_controller_test.go
Prune objects which exist in the cluster but are not managed by the operator anymore. For example, when the Jaeger Query Ingress is enabled and later disabled, the Ingress object should be removed from the cluster.
Resolves: #259
=> Prune unmanaged resources

controllers/tempo/tempostack_controller_test.go
PR #280 was based on an older version of the main branch where all unit tests passed, but after merging it to the latest main branch there were some errors due to refactorings.
=> Fix TestPruneIngress unit test

.github/workflows/continuous-integration.yaml
Unfortunately codecov is flaky lately, and it shouldn't affect the result of the unit test action.
=> Do not fail CI if codecov step fails

.chloggen/operand_metrics.yaml, .chloggen/operator_metrics.yaml, Makefile, bundle/openshift/manifests/tempo-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, bundle/openshift/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml, bundle/openshift/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml, bundle/openshift/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, config/overlays/openshift/kustomization.yaml, config/overlays/openshift/manager_auth_proxy_tls_patch.yaml, config/overlays/openshift/metrics_service_tls_patch.yaml, config/overlays/openshift/prometheus_role.yaml, config/overlays/openshift/prometheus_role_binding.yaml, config/overlays/openshift/service_monitor_patch.yaml, config/prometheus/monitor.yaml
* this also changes the namespace in the openshift bundle to `openshift-operators-redhat`
* in-cluster monitoring will only scrape metrics if the `openshift-operators-redhat` namespace has the `openshift.io/cluster-monitoring: "true"` label
Resolves: #334
=> Add ServiceMonitor for operator metrics

.chloggen/resources_on_gateway.yaml, internal/manifests/gateway/gateway.go, internal/manifests/manifestutils/resources.go, internal/manifests/manifestutils/resources_test.go
This PR assign resources to the tempo gateway
In order to determine what percentage of resources the gateway needs I did some experiments, stressed a tempo stack with a lot of spans, and some queries (this part was done manually) thought the gateway.
Then try to reach the stack ingestion/query limits with the assigned resources, based on the gateway consumption did the math.
We can find more about the experiments here: https://docs.google.com/spreadsheets/d/1rqsh2aKxP24FmgQmC9_Ld_qxtXpoNE7yLaoy1fzjRko/edit?usp=sharing
I have to round the numbers manually so the sum will be 1.0
Fixes #201
=> Assign resources to gateway

internal/manifests/config/build_test.go, internal/manifests/config/tempo-config.yaml
The log level shouldn't be debug by default.
For debugging sessions, users should be able to customize the tempo config directly by using the unmanaged mode proposed in #411
=> Do not set Tempo log level to debug

Makefile, hack/olm/catalog.yaml, hack/olm/subscription.yaml
Running `make olm/install-operator` on a fresh minikube/kind cluster will install OLM and setup tempo-operator with a single command. Useful for locally debugging OLM related issues.
=> Add OLM targets to Makefile

.chloggen/recover_resource_requests.yaml, bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, config/manager/manager.yaml
Recover the `resource.requests` field.
Solves #426
=> Recover the resource.requests as per OpenShift guidelines

internal/manifests/manifestutils/resources_test.go
Sometimes the floats aren't equal due to loss of precision, for example:
```
--- FAIL: TestResourceWithGatewaySum (0.00s)
resources_test.go:31:
Error Trace:	/home/runner/work/tempo-operator/tempo-operator/internal/manifests/manifestutils/resources_test.go:31
Error:      	Not equal:
expected: 1
actual  : 1.0000001
Test:       	TestResourceWithGatewaySum
```
https://github.com/grafana/tempo-operator/actions/runs/5089699823/jobs/9147650291
=> Fix float comparison in unit test

.chloggen/rename_operator_deployment.yaml, Makefile, bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml, config/default/manager_config_patch.yaml, config/default/manager_webhook_patch.yaml, config/manager/manager.yaml, config/overlays/openshift/manager_auth_proxy_tls_patch.yaml
Commit 7fa448aa2bf28fb44ecf0cb530f7a530855894d6 added additional labels to the operator deployment and its selector field.
Unfortunately the selector field is immutable, and when OLM tries to patch the deployment while upgrading, Kubernetes will reject this update.
A workaround is to rename the deployment, as suggested here: https://github.com/operator-framework/operator-lifecycle-manager/issues/952
=> Rename operator deployment

.chloggen/fix_status_condition_metric.yaml, apis/tempo/v1alpha1/tempostack_types.go, config/overlays/community/kustomization.yaml, controllers/tempo/tempostack_controller.go, internal/status/components.go, internal/status/components_test.go, internal/status/conditions.go, internal/status/status.go
In some cases not all status condition metrics were updated, because for example:
A TempoStack CR gets created with an invalid storage secret (creating a Degraded status condition). Later this CR is deleted, a storage secret is created and a new TempoStack instance is created. Then this TempoStack instance doesn't have the degraded condition in the status.Conditions list.
I also updated a few references of 'Microservices' and fixed a typo in a function name.
=> Always set all status condition values in the tempostack_status_condition metric

tests/Dockerfile
Add's step to tests/Dockerfile to build bin/manger binary required by e2e tests.
=> Update tests/Dockerfile to build bin/manager required by e2e tests

Makefile
This fixes https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/40691/rehearse-40691-pull-ci-openshift-grafana-tempo-operator-main-images/1673671682566393856
=> Fix installation of tooling on prow.ci

.chloggen/fix_servicemonitor_tls.yaml, internal/manifests/servicemonitor/servicemonitor.go, internal/manifests/servicemonitor/servicemonitor_test.go
This PR fixes the location of the TLS certificates for the ServiceMonitors.
In #387 the certificate names were changed to `*-mtls`, and because `naming.Name` was used instead of `naming.TLSSecretName` to get the certificate name, the ServiceMonitors used to point to non existing certificates.
The PR also updates the gateway's TLS certificate location in the ServiceMonitor (depends on PR #480).
=> Fix TLS configuration of ServiceMonitors

.chloggen/validate_createPrometheusRules.yaml, apis/tempo/v1alpha1/tempostack_webhook.go, apis/tempo/v1alpha1/tempostack_webhook_test.go
Validate if createServiceMonitors is enabled when enabling createPrometheusRules in the webhook
=> Validate if createServiceMonitors is enabled when enabling createPrometheusRules in the webhook

.github/workflows/continuous-integration.yaml, .github/workflows/publish-images.yaml, CONTRIBUTING.md, Makefile, README.md
For local development, the following invocation:
```
IMG_PREFIX=docker.io/${USER} OPERATOR_VERSION=$(date +%s).0.0 make docker-build docker-push deploy reset
```
Builds and deploys the operator to the current cluster and resets all generated files.
Resolves: #62
=> Add new reset Makefile target, cleanup GitHub Action workflows

.chloggen/expose-query-grpc.yaml, config/samples/tempo_v1alpha1_tempostack.yaml, internal/manifests/queryfrontend/query_frontend.go, internal/manifests/queryfrontend/query_frontend_test.go, tests/e2e/smoketest-with-jaeger/01-assert.yaml
=> Expose the query GRPC port

Makefile, config/docs/templates/pkg.tpl, docs/operator/api.md, docs/operator/feature-gates.md
The API docs will be published only as .md files and referenced from https://grafana.com/docs/tempo/next/setup/operator/
=> Publish API docs only as a md file

bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, config/manager/manager.yaml
The command is redundant, as it is specified in the ENTRYPOINT of the Dockerfile.
=> Remove command from pod spec in CSV

.chloggen/prune_operator_manifests.yaml, bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, cmd/start/main.go, config/rbac/role.yaml, controllers/tempo/operator_controller.go, controllers/tempo/operator_controller_test.go, controllers/tempo/tempostack_controller.go
Remove operator ServiceMonitor and PrometheusRule when operator deployment is removed, by setting the owner references on the operator manifests.
=> Remove operator ServiceMonitor and PrometheusRule when operator deployment is removed

CONTRIBUTING.md, apis/tempo/v1alpha1/tempostack_types.go
The path specified in `statusDescriptors` in the CSV must be always present, otherwise a warning is shown in the UI.
This fixes the following issue in case no pods were created due to a configuration error: 
I also added instructions to deploy the operator via OLM in the `CONTRIBUTING.md` file.
=> Always render the PodStatusMaps in the CR status

.chloggen/disable_mtls.yaml, bundle/community/manifests/tempo-operator-manager-config_v1_configmap.yaml, bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo-operator-manager-config_v1_configmap.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, config/overlays/community/controller_manager_config.yaml, config/overlays/openshift/controller_manager_config.yaml, tests/e2e-openshift/monitoring/02-assert.yaml, tests/e2e-openshift/multitenancy/01-assert.yaml, tests/e2e/gateway/02-assert.yaml, tests/e2e/smoketest-with-jaeger/03-verify-traces.yaml
Disable mTLS by default, to allow connections from Grafana to the query-frontend component.
Resolves: #552
=> Disable mTLS by default, to allow connections from Grafana to the query-frontend

.chloggen/pprof.yaml, cmd/start/main.go
update operator deployment, add `--pprof-addr=0.0.0.0:6060` argument
```
kubectl port-forward -n tempo-operator-system deployment/tempo-operator-controller 6060
go install github.com/google/pprof@latest
pprof -http=localhost:8080 localhost:6060/debug/pprof/heap
```
Resolves: #242
=> Add pprof flag to optionally expose pprof data

bundle/community/manifests/tempo-operator-manager-config_v1_configmap.yaml, bundle/openshift/manifests/tempo-operator-manager-config_v1_configmap.yaml, config/overlays/community/controller_manager_config.yaml, config/overlays/openshift/controller_manager_config.yaml
The new image has fix https://github.com/observatorium/api/pull/570 that is needed to make the Jaeger monitor tab work with Gateway
=> Update gateway image

.chloggen/otlp_http.yaml, internal/manifests/distributor/distributor.go, internal/manifests/distributor/distributor_test.go, internal/manifests/manifestutils/constants.go, tests/e2e/generate/01-assert.yaml, tests/e2e/smoketest-with-jaeger/01-assert.yaml
Required e.g. for running the hotrod example application
```
$ docker run --network=host -e OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo-simplest-distributor.default.svc.cluster.local:4318 jaegertracing/example-hotrod:1.46 all --otel-exporter=otlp
```
=> Expose the OTLP HTTP port in the distributor service

.github/workflows/continuous-integration.yaml
This reverts commit 7de479668c4e6c57d46b745c7b79e1ac6f74f714.
v4 is not released yet (or got un-released?), the CI run worked fine 4 days ago:
https://github.com/grafana/tempo-operator/actions/runs/6192772421/job/16813342328?pr=615
=> Revert "build(deps): Bump codecov/codecov-action from 3 to 4 (#615)"

.chloggen/redmetrics-cluster-role.yaml, bundle/openshift/manifests/tempo-operator-manager-rolebinding-cluster-monitoring-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, config/overlays/openshift/kustomization.yaml, config/overlays/openshift/role_binding_cluster_monitoring_view.yaml, internal/manifests/queryfrontend/query_frontend.go, internal/manifests/queryfrontend/query_frontend_test.go, tests/e2e-openshift/red-metrics/02-assert.yaml, tests/e2e-openshift/red-metrics/02-install-tempo.yaml
Resolves #526 
Depends on https://github.com/jaegertracing/jaeger/pull/4726 and released tempo-query with the feature.
Notable changes:
- tempo operator SA on OCP gets `cluster-monitoring-view` cluster role - it needs it because it needs to create the same `clusterrolebinding` for instances.
- tempo instance SA gets `cluster-monitoring-view` cluster role - needed to access metrics for the monitor tab
=> Use tempo SA to query RED metrics from OpenShift monitoring stack

apis/tempo/v1alpha1/tempostack_webhook.go
Run validation in webhook only if CA is not empty.
=> Fix object storage CA validation

tests/e2e/gateway/00-assert.yaml, tests/e2e/gateway/00-install.yaml
Replace the official dex image with one providing support for `linux/s390x`.
More context in #643.
=> [chore] Replace official dex image

tests/e2e-openshift/red-metrics/03-assert.yaml
```
$ kuttl test --test=red-metrics --timeout=300 tests/e2e-openshift/
2023/11/03 10:06:51 kutt-test config testdirs is overridden with args: [ tests/e2e-openshift/ ]
=== RUN   kuttl
harness.go:462: starting setup
harness.go:252: running tests using configured kubeconfig.
harness.go:275: Successful connection to cluster at: https://REDACTED:6443
harness.go:360: running tests
harness.go:73: going to run test suite with timeout of 300 seconds for each step
harness.go:372: testsuite: tests/e2e-openshift/ has 4 tests
=== RUN   kuttl/harness
=== RUN   kuttl/harness/red-metrics
=== PAUSE kuttl/harness/red-metrics
=== CONT  kuttl/harness/red-metrics
logger.go:42: 10:06:55 | red-metrics | Ignoring check_user_workload_monitoring.sh as it does not match file name regexp: …
```
=> [Chore] Fix RED metrics test case.

.chloggen/reduce_certrotation_loglevel.yaml, controllers/tempo/certrotation_controller.go, internal/certrotation/handlers/rotate_certs.go
Checking/skipping/building of certificate manifests is run for every reconciliation and is filling up the logs unnecessarily. For debugging purposes, the log level can be increased.
Resolves: #623
=> Reduce log level of certrotation messages

.github/workflows/prepare-release.yaml, .github/workflows/release.yaml, RELEASE.md
This new process is as follows:
- Trigger "Prepare Release" GitHub action from the GitHub UI, you need to specify the new version.
- This will create a new branch releases/x.y.z, where x.y.z is the new release
- This also will create a new PR, witht he new bundle, the CHANGELOG, and all the neccesary modifications.
- Once we test this on openshift and we are happy, we can merge the PR
The release GitHub action will take place
This GH action will be triggered only when the PR that gets merged is from releases/*., the source and destination are the the same repository, and the author of the PR is a GitHub action.
And this workflow follows the regular process, created release on GH and create the tag (we don't need to create the tag manually anymore)
Also this will trigger the OLM publish …
=> New Release Process (Semi automatic way)

.github/workflows/release.yaml, .github/workflows/reusable-operator-hub-release.yaml
It will be good to merge first https://github.com/grafana/tempo-operator/pull/681
Also I'm not sure how to test this before release
=> Automate release push to OLM in tempo-operator

.chloggen/unset_images_in_cr.yaml, apis/tempo/v1alpha1/tempostack_webhook.go, apis/tempo/v1alpha1/tempostack_webhook_test.go, cmd/generate/main.go, cmd/generate/main_test.go, controllers/tempo/tempostack_create_or_update.go, internal/manifests/compactor/compactor.go, internal/manifests/config/build.go, internal/manifests/config/build_test.go, internal/manifests/distributor/distributor.go, internal/manifests/gateway/gateway.go, internal/manifests/gateway/gateway_test.go, internal/manifests/gateway/openshift.go, internal/manifests/gateway/openshift_test.go, internal/manifests/ingester/ingester.go, internal/manifests/manifestutils/params.go, internal/manifests/querier/querier.go, internal/manifests/queryfrontend/query_frontend.go, internal/manifests/queryfrontend/query_frontend_test.go, internal/manifests/servicemonitor/servicemonitor.go, internal/manifests/servicemonitor/servicemonitor_test.go, internal/tlsprofile/options.go, internal/upgrade/upgrade.go, internal/upgrade/upgrade_test.go, internal/upgrade/v0_6_0.go, internal/upgrade/versions.go, tests/e2e/generate/01-generate.yaml, tests/e2e/generate/config.yaml
Various tools are capable of automatic rebuilding of images in case of
CVEs (e.g. freshmaker [1]). These tools rebuild all images and update
the RELATED_IMAGE_ environment variables in the CSV accordingly (ref. #638).
However, they do not update the version field (the
github.com/grafana/tempo-operator/internal/version.operatorVersion LDFLAG
when building the operator), they only update the version of the CSV.
Therefore the upgrade process won't run, and nothing will replace the
images field in the TempoStack CRs, i.e. the tempo/tempo-query/gateway
pods are not updated with the new image version.
This PR modifies the handling to use the default images if the image
field of the TempoStack CR is unset. Then the operator will use the image
from RELATED_IMAGE_ env variables, and the containers …
=> Unset (default) images in TempoStack CR

tests/e2e-openshift/monitoring/02-assert.yaml
This assert is not required (please correct me if I'm missing something).
The test fails on CRC without this change.
=> drop bearerTokenSecret assert in e2e-openshift/monitoring test

.github/workflows/reusable-operator-hub-release.yaml
https://api.github.com/users/tempooperatorbot
=> Fix tempooperatorbot mail address

.github/workflows/publish-images.yaml
It seems that even if creating a release creates a tag, The publish image was not triggered. it seems like you need to explicitly push the tag to trigger it.
In this PR I also add the release published event  (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release) in order to trigger this workflow with the new approach.
I had to run manually for this release in order to have the image published.
@andreasgerstmayr  please review.
=> Trigger publish images when release happens

tests/e2e-openshift/monitoring/03-generate-traces.yaml, tests/e2e-openshift/multitenancy/04-verify-traces.yaml, tests/e2e-upgrade/upgrade/50-verify-traces.yaml, tests/e2e-upgrade/upgrade/70-verify-traces-after-upgrade.yaml, tests/e2e/custom-ca/03-verify-traces.yaml, tests/e2e/receivers-mtls/04-verify-traces.yaml, tests/e2e/receivers-tls/04-verify-traces.yaml, tests/e2e/smoketest-with-jaeger/04-verify-traces.yaml
* Replace test image curl-jq with [tempo-operator/test-utils:main](https://github.com/grafana/tempo-operator/pkgs/container/tempo-operator%2Ftest-utils) so that the tests can also be run on a non-amd64 Kubernetes/OpenShift cluster. 
* Fix monitoring test case failing with LIVE_TRACES_EXCEEDED issue. 
Tests passed on OpenShift 4.14 cluster:
PASS: kuttl (268.37s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/gateway (60.99s)
--- PASS: kuttl/harness/generate (66.02s)
--- PASS: kuttl/harness/reconcile (122.35s)
--- PASS: kuttl/harness/route (148.60s)
--- PASS: kuttl/harness/monitoring (148.91s)
--- PASS: kuttl/harness/receivers-tls (156.43s)
--- PASS: kuttl/harness/smoketest-with-jaeger (156.67s)
--- PASS: kuttl/harness/red-metrics (160.08s)
--- PASS: kuttl/harness/multitenancy …
=> [Chore] Replace curl-jq image with multi-arch built image tempo-operator/test-utils:main

.chloggen/divide_limit_with_replicas.yaml, internal/manifests/compactor/compactor.go, internal/manifests/compactor/compactor_test.go, internal/manifests/distributor/distributor.go, internal/manifests/gateway/gateway.go, internal/manifests/ingester/ingester.go, internal/manifests/manifestutils/resources.go, internal/manifests/manifestutils/resources_test.go, internal/manifests/querier/querier.go, internal/manifests/querier/querier_test.go, internal/manifests/queryfrontend/query_frontend.go
Resolves https://github.com/grafana/tempo-operator/issues/721
=> Divide assigned limits with replicas

tests/e2e-openshift/monitoring/03-generate-traces.yaml, tests/e2e-openshift/multitenancy/03-generate-traces.yaml, tests/e2e-upgrade/upgrade/40-generate-traces.yaml, tests/e2e/compatibility/03-generate-traces.yaml, tests/e2e/custom-ca/02-generate-traces.yaml, tests/e2e/receivers-mtls/03-generate-traces.yaml, tests/e2e/receivers-tls/03-generate-traces.yaml
Multiarch image support for Telemetrygen is added by PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29905 and the latest stable version of [Telemetrygen v0.92.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/pkgs/container/opentelemetry-collector-contrib%2Ftelemetrygen/165347009?tag=v0.92.0 ) is released with the multiarch support. I have updated the e2e tests in this PR so that we can run them for different architectures without performing any additional steps.
=> [Chore] Update e2e tests to use multiarch Telemetrygen v0.92.0

tests/e2e-openshift/red-metrics/02-assert.yaml, tests/e2e-openshift/red-metrics/02-install-otel-collector.yaml, tests/e2e-openshift/red-metrics/03-assert.yaml, tests/e2e-openshift/red-metrics/05-assert.yaml, tests/e2e-openshift/red-metrics/05-install-generate-traces.yaml, tests/e2e-openshift/red-metrics/06-assert.yaml, tests/e2e-openshift/red-metrics/07-assert.yaml, tests/e2e-openshift/red-metrics/check_alert.sh, tests/e2e-openshift/red-metrics/check_metrics.sh
The PR updates the red-metrics test case to test Span RED alerts using prometheusrule and verify the metrics generated. 
```
kuttl test --timeout=300 --test=red-metrics tests/e2e-openshift
2024/01/12 14:09:35 kutt-test config testdirs is overridden with args: [ tests/e2e-openshift ]
=== RUN   kuttl
harness.go:462: starting setup
harness.go:252: running tests using configured kubeconfig.
harness.go:275: Successful connection to cluster at: https://api.REDACTED:6443
harness.go:360: running tests
harness.go:73: going to run test suite with timeout of 300 seconds for each step
harness.go:372: testsuite: tests/e2e-openshift has 4 tests
=== RUN   kuttl/harness
=== RUN   kuttl/harness/red-metrics
=== PAUSE kuttl/harness/red-metrics
=== CONT  kuttl/harness/red-metrics
logger.go:42: 14:09:42 | …
```
=> [Chore] Test Span RED metrics and alerts.

tests/e2e-openshift/multitenancy/01-assert.yaml, tests/e2e/gateway/03-assert.yaml
Update the test cases due to changes in PR https://github.com/grafana/tempo-operator/pull/705
=> [Chore] Fix e2e gateway and multitenancy tests.

controllers/tempo/storage.go, internal/manifests/config/build.go, internal/manifests/distributor/distributor.go, internal/manifests/distributor/distributor_test.go, internal/manifests/gateway/gateway.go, internal/manifests/gateway/gateway_test.go, internal/manifests/manifestutils/constants.go, internal/manifests/manifestutils/params.go, internal/manifests/manifestutils/paths.go, internal/manifests/manifestutils/service.go, internal/manifests/manifestutils/storage.go, internal/manifests/manifestutils/storage_test.go, internal/manifests/queryfrontend/query_frontend.go, internal/manifests/queryfrontend/query_frontend_test.go, tests/e2e/custom-ca/01-assert.yaml, tests/e2e/custom-ca/01-install-tempo.yaml
We're currently managing three different sets of certificates:
* internal communication between components
* receiver TLS
* storage TLS
Let's unify them with common paths and key names in the ConfigMap/Secrets.
Except for changing the storage CA mountpoint from `/var/run/tls/storage` to `/var/run/tls/storage/ca`, all other manifests should be unmodified.
=> Unify TLS paths and key names

internal/manifests/monolithic/configmap.go, internal/manifests/monolithic/statefulset.go
2 additional nil pointer checks for abundance of caution (storage should always be set in Default() in the controller)
=> Additional nil pointer checks

tests/e2e-openshift/red-metrics/06-assert.yaml, tests/e2e-openshift/red-metrics/06-intall-assert-job.yaml
Sets the required clusterrolebinding cluster-monitoring-view to query the metrics from Thanos querier. 
```
--- PASS: kuttl (238.99s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/red-metrics (236.12s)
PASS
```
=> [Chore] Fix red-metrics test case

tests/e2e/monolithic-memory/03-generate-traces.yaml, tests/e2e/monolithic-memory/05-verify-traces-grafana.yaml, tests/e2e/monolithic-pv/03-generate-traces.yaml, tests/e2e/monolithic-s3-tls/03-generate-traces.yaml
Updates tests to use multiarch images so that we can run them on ARM and IBM P and Z clusters.
Tested on ARM cluster:
```
--- PASS: kuttl (640.49s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/monolithic-ingestion-mtls (99.97s)
--- PASS: kuttl/harness/multitenancy (129.50s)
--- PASS: kuttl/harness/compatibility (156.81s)
--- PASS: kuttl/harness/receivers-mtls (157.96s)
--- PASS: kuttl/harness/monolithic-s3-tls (116.83s)
--- PASS: kuttl/harness/monolithic-pv (107.96s)
--- PASS: kuttl/harness/monolithic-memory (104.70s)
--- PASS: kuttl/harness/reconcile (129.98s)
--- PASS: kuttl/harness/gateway (61.34s)
--- PASS: kuttl/harness/generate (62.52s)
--- PASS: kuttl/harness/monitoring (147.11s)
--- PASS: kuttl/harness/route (44.64s)
--- PASS: kuttl/harness/receivers-tls (163.48s)
--- …
```
=> [Chore] Update tests to use multiarch images.

.github/workflows/changelog.yaml, .github/workflows/continuous-integration.yaml, .github/workflows/e2e.yaml, .github/workflows/prepare-release.yaml, .github/workflows/publish-test-utils-image.yaml, .github/workflows/release.yaml, .github/workflows/reusable-publish-images.yaml, .github/workflows/scorecard.yaml
use Go version of go.mod in GitHub actions
=> [chore] use Go version of go.mod in GitHub actions

tests/Dockerfile
Fixes the issue with image build. Refer https://github.com/openshift/grafana-tempo-operator/pull/17
=> [Chore] Fix Tempo tests runner Dockerfile

tests/Dockerfile
Installs kuttl in the Tempo tests runner image used in OCP CI for running tests for older operator version. For running tests for a older operator version, a cut-off commit from the repository is used.
=> [Chore] Install kuttl to run tests for older operator version

.github/workflows/continuous-integration.yaml
Fixes:
```
/usr/bin/tar -xf /home/runner/work/_temp/ab5fc90b-99a4-43c1-8181-4d8960a26ad0/cache.tzst -P -C /home/runner/work/tempo-operator/tempo-operator --use-compress-program unzstd
Received 223785415 of 223785415 (100.0%), 106.6 MBs/sec
/usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.32.0/README.md: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.32.0/integration_test.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.32.0/protoadapt/convert.go: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.32.0/PATENTS: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.32.0/encoding/bench_test.go: …
```
=> fix golint

CONTRIBUTING.md, RELEASE.md
It's the default value, no need to specify it.
=> [chore] drop OPERATOR_NAMESPACE=tempo-operator-system from example commands

.chloggen/grafana_cross_namespace.yaml, internal/manifests/grafana/datasource.go, internal/manifests/grafana/datasource_test.go, internal/manifests/monolithic/grafana_datasource_test.go
Support Grafana instances in a different namespace
Otherwise the `Grafana` CR must be in the same namespace as the `TempoStack` CR.
=> Support Grafana instances in a different namespace

internal/manifests/grafana/datasource.go, internal/webhooks/tempostack_webhook.go, internal/webhooks/tempostack_webhook_test.go
It is broken when the gateway is enabled due to missing authentication.
=> Disable Grafana data source creation if gateway is enabled

.chloggen/monolithic_custom_sa.yaml, apis/tempo/v1alpha1/tempomonolithic_types.go, bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/community/manifests/tempo.grafana.com_tempomonolithics.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo.grafana.com_tempomonolithics.yaml, config/crd/bases/tempo.grafana.com_tempomonolithics.yaml, config/manifests/community/bases/tempo-operator.clusterserviceversion.yaml, config/manifests/openshift/bases/tempo-operator.clusterserviceversion.yaml, controllers/tempo/tempomonolithic_controller.go, docs/operator/api.md, docs/spec/tempo.grafana.com_tempomonolithics.yaml, internal/manifests/monolithic/build.go, internal/manifests/monolithic/statefulset.go, internal/manifests/monolithic/statefulset_test.go, internal/webhooks/tempomonolithic_webhook.go, internal/webhooks/tempomonolithic_webhook_test.go
Support custom ServiceAccount in TempoMonolithic CR
Depends on #815
=> Support custom ServiceAccount in TempoMonolithic CR

tests/e2e-openshift/multitenancy/01-assert.yaml
The test is failing in OCP CI. Refer https://github.com/openshift/grafana-tempo-operator/pull/25 
The PR fixes the asserts to use the named ports.
=> [Chore] Fix multitenancy test

internal/manifests/monolithic/build.go, internal/manifests/monolithic/configmap.go, internal/manifests/monolithic/configmap_test.go, internal/manifests/monolithic/statefulset.go, internal/manifests/monolithic/statefulset_test.go
When the gateway is enabled, we need to add additional annotations with file checksums to the tempo statefulset.
=> Monolithic: support multiple annotations (multiple config file checksums)

.chloggen/monolithic_internal_server.yaml, internal/manifests/manifestutils/constants.go, internal/manifests/monolithic/configmap.go, internal/manifests/monolithic/configmap_test.go, internal/manifests/monolithic/statefulset.go, internal/manifests/monolithic/statefulset_test.go
If the gateway is enabled, we want to prevent direct connections to the
Tempo API by making it listen to localhost. All connections must go via
gateway for authentication and authorization.
The internal Tempo server listens on all interfaces and responds to
health checks.
=> Monolithic: use internal Tempo server

.chloggen/monolithic_tlsprofile.yaml, apis/config/v1alpha1/projectconfig_types.go, cmd/root.go, controllers/tempo/tempomonolithic_controller.go, controllers/tempo/tempomonolithic_controller_test.go, controllers/tempo/tempostack_controller.go, controllers/tempo/tempostack_controller_test.go, controllers/tempo/tempostack_create_or_update.go, internal/manifests/monolithic/configmap.go, internal/manifests/monolithic/configmap_test.go, internal/manifests/monolithic/options.go, internal/tlsprofile/get.go, internal/tlsprofile/get_test.go
Support TLS Profile with TempoMonolithic CR
=> Support TLS Profile with TempoMonolithic CR

tests/e2e-openshift-ossm/ossm-monolithic-otel/verify-traces.yaml, tests/e2e-openshift-ossm/ossm-tempostack-otel/verify-traces.yaml, tests/e2e-openshift-ossm/ossm-tempostack/verify-traces.yaml
Update START_MICROS in the verfiy-traces step of the test case. The test case is failing when running from OCP CI. https://github.com/openshift/release/pull/51132
=> [Chore] Fix interop test cases for OSSM.

tests/e2e-openshift/monolithic-multitenancy-openshift/01-assert.yaml, tests/e2e-openshift/monolithic-multitenancy-openshift/01-install-tempo.yaml, tests/e2e-openshift/monolithic-multitenancy-openshift/02-install-otelcol.yaml, tests/e2e-openshift/monolithic-multitenancy-openshift/04-verify-traces.yaml
All OpenShift multitenancy tests create cluster-scoped resources (e.g. ClusterRole `tempo-<name>-gateway`), therefore we must use unique names across the cluster, otherwise running the e2e test suite in parallel will fail randomly.
=> [chore] e2e: update tempo instance name to avoid race condition

Makefile, tests/Dockerfile
The PR bumps the Chainsaw version to v0.2.0 and adds the platform var in the bundle build, which fixes issues when building on platforms like Mac with Apple Silicon.
=> [Chore] Bump Chainsaw version and update Makefile to add platform var for bundle build. 

tests/e2e-openshift-ossm/ossm-tempostack-otel/install-tempo-assert.yaml, tests/e2e-openshift-ossm/ossm-tempostack/install-tempo-assert.yaml, tests/e2e-openshift/monitoring/02-assert.yaml, tests/e2e-openshift/route/chainsaw-test.yaml, tests/e2e-openshift/route/install-tempo-assert.yaml, tests/e2e-openshift/route/install-tempo.yaml
Fix test failures caused due to oauth proxy on single tenant feature. https://github.com/grafana/tempo-operator/pull/910
=> [Chore] Update tests for feature oauth proxy on single tenant

tests/e2e-openshift/monolithic-route/chainsaw-test.yaml, tests/e2e-openshift/monolithic-route/install-tempo-assert.yaml, tests/e2e-openshift/monolithic-route/install-tempo.yaml, tests/e2e-openshift/monolithic-single-tenant-auth/chainsaw-test.yaml, tests/e2e-openshift/monolithic-single-tenant-auth/generate-traces-assert.yaml, tests/e2e-openshift/monolithic-single-tenant-auth/generate-traces.yaml, tests/e2e-openshift/monolithic-single-tenant-auth/install-tempo-assert.yaml, tests/e2e-openshift/monolithic-single-tenant-auth/install-tempo.yaml, tests/e2e-openshift/monolithic-single-tenant-auth/verify-traces-jaeger-assert.yaml, tests/e2e-openshift/monolithic-single-tenant-auth/verify-traces-jaeger.yaml, tests/e2e-openshift/monolithic-single-tenant-auth/verify-traces-traceql-assert.yaml, tests/e2e-openshift/monolithic-single-tenant-auth/verify-traces-traceql.yaml, tests/e2e-openshift/tempo-single-tenant-auth/chainsaw-test.yaml, tests/e2e-openshift/tempo-single-tenant-auth/generate-traces-assert.yaml, tests/e2e-openshift/tempo-single-tenant-auth/generate-traces.yaml, tests/e2e-openshift/tempo-single-tenant-auth/install-storage-assert.yaml, tests/e2e-openshift/tempo-single-tenant-auth/install-storage.yaml, tests/e2e-openshift/tempo-single-tenant-auth/install-tempo-assert.yaml, tests/e2e-openshift/tempo-single-tenant-auth/install-tempo.yaml, tests/e2e-openshift/tempo-single-tenant-auth/verify-traces-jaeger-assert.yaml, tests/e2e-openshift/tempo-single-tenant-auth/verify-traces-jaeger.yaml, tests/e2e-openshift/tempo-single-tenant-auth/verify-traces-traceql-assert.yaml, tests/e2e-openshift/tempo-single-tenant-auth/verify-traces-traceql.yaml
* Add test cases for TempoStack and Monolithic Tempo with single tenant oauth. 
* Add test case for Monolithic instance with route enabled and check the Monolithic instance enables oauth by default.
Tested on OpenShift 4.14
```
--- PASS: chainsaw (1503.82s)
--- PASS: chainsaw/ossm-monolithic-otel (328.39s)
--- PASS: chainsaw/ossm-tempostack (349.48s)
--- PASS: chainsaw/ossm-tempostack-otel (393.22s)
--- PASS: chainsaw/monitoring (206.07s)
--- PASS: chainsaw/red-metrics (226.67s)
--- PASS: chainsaw/monolithic-route (76.89s)
--- PASS: chainsaw/monolithic-memory (97.02s)
--- PASS: chainsaw/monolithic-ingestion-mtls (99.34s)
--- PASS: chainsaw/monolithic-multitenancy-openshift (99.34s)
--- PASS: chainsaw/monolithic-single-tenant-auth (109.93s)
--- PASS: chainsaw/route (147.23s)
--- PASS: …
```
=> [Chore] Add tests for Tempo single tenant oauth

tests/e2e-openshift/monitoring/check_metrics.sh, tests/e2e-openshift/red-metrics/check_metrics.sh
In OpenShift 4.16 tokens for service account are not generated by default and we have to now use the TokenRequest API to create token. The PR fixes the check_metrics.sh script to create a token from prometheus-user-workload SA. Tested on OpenShift 4.16 and 4.15
```
--- PASS: chainsaw (1680.86s)
--- PASS: chainsaw/ossm-monolithic-otel (455.74s)
--- PASS: chainsaw/ossm-tempostack (368.49s)
--- PASS: chainsaw/ossm-tempostack-otel (404.15s)
--- PASS: chainsaw/monitoring (215.61s)
--- PASS: chainsaw/red-metrics (236.87s)
--- PASS: chainsaw/route (51.14s)
--- PASS: chainsaw/gateway (68.05s)
--- PASS: chainsaw/monolithic-multitenancy-openshift (115.89s)
--- PASS: chainsaw/monolithic-memory (116.76s)
--- PASS: chainsaw/monolithic-pv (120.70s)
--- PASS: chainsaw/monolithic-s3-tls (128.72s)
--- …
```
=> [Chore] FIx tests querying OpenShift user workload monitoring stack

go.mod
The PR fixes the Golang version in go.mod as the wrong version is causing our rebase job on the fork to [fail](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-eng-rebasebot-main-tempo-operator/1808092991135420416/artifacts/tempo-operator/tempo-operator/build-log.txt)
=> [Chore] Fix Golang version in go.mod

tests/e2e-openshift/multitenancy/01-assert.yaml
The PR fixes the multitenancy test case by removing the duplicate --tls.client-auth-type=NoClientCert from the assert.
=> [Chore] Fix multitenancy test case

.chloggen/aws-sts-monolithic.yaml, .chloggen/aws-sts-tempostack.yaml, cmd/generate/main.go, internal/handlers/storage/secret.go, internal/handlers/storage/secret_test.go, internal/handlers/storage/storage.go, internal/manifests/compactor/compactor.go, internal/manifests/config/build.go, internal/manifests/config/build_test.go, internal/manifests/config/configmap_test.go, internal/manifests/config/tempo-config.yaml, internal/manifests/ingester/ingester.go, internal/manifests/manifests.go, internal/manifests/manifests_test.go, internal/manifests/manifestutils/annotations.go, internal/manifests/manifestutils/params.go, internal/manifests/manifestutils/storage.go, internal/manifests/manifestutils/storage_test.go, internal/manifests/monolithic/configmap.go, internal/manifests/monolithic/configmap_test.go, internal/manifests/monolithic/serviceaccount.go, internal/manifests/monolithic/serviceaccount_test.go, internal/manifests/monolithic/statefulset.go, internal/manifests/oauthproxy/oauth_proxy.go, internal/manifests/oauthproxy/oauth_proxy_test.go, internal/manifests/querier/querier.go, internal/manifests/queryfrontend/query_frontend.go, internal/manifests/serviceaccount/serviceaccount.go, internal/manifests/serviceaccount/serviceaccount_test.go, internal/webhooks/tempostack_webhook_test.go
Resolves #553 
https://issues.redhat.com/browse/TRACING-4227
Test instructions:
```
kubectl create namespace tempo-operator-system
IMG_PREFIX=docker.io/pavolloffay OPERATOR_VERSION=$(date +%s).0.0 BUNDLE_VARIANT=openshift make docker-build docker-push bundle bundle-build bundle-push olm-deploy
kubectl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
name: aws-sts
stringData:
bucket: tempoploffay
region: us-east-2
role_arn: arn:aws:iam::TBD:role/ploffay-simplest
type: Opaque
EOF
kubectl apply -f - <<EOF
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
name: simplest
spec:
storage:
secret:
name: aws-sts
type: s3
storageSize: 1Gi
resources:
total:
limits:
memory: 2Gi
cpu: 2000m
template:
queryFrontend:
jaegerQuery:
enabled: true
ingress:
type: route
EOF
kubectl apply …
```
=> Add support for AWS STS

.chloggen/tls_cert_serv_mono.yaml, apis/tempo/v1alpha1/tempomonolithic_types.go, bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/community/manifests/tempo.grafana.com_tempomonolithics.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo.grafana.com_tempomonolithics.yaml, config/crd/bases/tempo.grafana.com_tempomonolithics.yaml, config/manifests/community/bases/tempo-operator.clusterserviceversion.yaml, config/manifests/openshift/bases/tempo-operator.clusterserviceversion.yaml, docs/spec/tempo.grafana.com_tempomonolithics.yaml, internal/manifests/monolithic/build.go, internal/manifests/monolithic/configmap.go, internal/manifests/monolithic/services.go, internal/manifests/monolithic/services_test.go, internal/manifests/monolithic/util.go, tests/e2e-openshift/tls-monolithic-singletenant/00-assert.yaml, tests/e2e-openshift/tls-monolithic-singletenant/00-install-storage.yaml, tests/e2e-openshift/tls-monolithic-singletenant/01-assert.yaml, tests/e2e-openshift/tls-monolithic-singletenant/01-install-tempo.yaml, tests/e2e-openshift/tls-monolithic-singletenant/02-assert.yaml, tests/e2e-openshift/tls-monolithic-singletenant/02-install-otelcol.yaml, tests/e2e-openshift/tls-monolithic-singletenant/03-assert.yaml, tests/e2e-openshift/tls-monolithic-singletenant/03-generate-traces.yaml, tests/e2e-openshift/tls-monolithic-singletenant/04-assert.yaml, tests/e2e-openshift/tls-monolithic-singletenant/04-verify-traces.yaml, tests/e2e-openshift/tls-monolithic-singletenant/chainsaw-test.yaml
This is the monolithic version 
Depends on https://github.com/grafana/tempo-operator/pull/977
=> Use openshift sertvice annotation when gateway is disabled (monolithic)

tests/Dockerfile
The PR updates the Dockerfile to add steps for installing AWS, Azure and Google Cloud CLI, which will be used in STS support for Tempo tests. Also bump the Chainsaw version.
=> [Chore] Update the OCP CI tests runner Dockerfile

internal/manifests/monolithic/build.go, tests/e2e-openshift/tls-monolithic-singletenant/01-install-tempo.yaml, tests/e2e-openshift/tls-monolithic-singletenant/02-install-otelcol.yaml, tests/e2e-openshift/tls-monolithic-singletenant/03-generate-traces.yaml
This fixes https://issues.redhat.com/browse/TRACING-4487 
There is one note here: We currently don't support mTLS for OpenShift service cert certificates. Our current implementation of mTLS is enabled when the user specify a CA, but in this case none of them are provided.
Solution:
I think we need to add a new field to the `TLSSpec` , something like `clientVerification`: true/false . This is off course a breaking change. We need to update all the current users that specified the CA , with the new field to true. I'll address all of this in a separate PR.
@andreasgerstmayr Please let me know what do you think.
=> Fix TLS on monolithic deployment

tests/e2e-openshift/tempostack-resources/chainsaw-test.yaml, tests/e2e-openshift/tempostack-resources/install-storage-assert.yaml, tests/e2e-openshift/tempostack-resources/install-storage.yaml, tests/e2e-openshift/tempostack-resources/install-tempostack-assert.yaml, tests/e2e-openshift/tempostack-resources/install-tempostack.yaml, tests/e2e-openshift/tempostack-resources/update-tempostack-assert.yaml, tests/e2e-openshift/tempostack-resources/update-tempostack.yaml, tests/e2e/monolithic-receivers-tls/chainsaw-test.yaml
The test will help us to detect regression in setting the resources for the components.
```
--- PASS: chainsaw/tempostack-resources (196.99s)
PASS
- Passed  tests 1
Done.
```
=> [Chore]Test TempoStack global and per-component resources allocation

tests/e2e-openshift/monitoring-monolithic/chainsaw-test.yaml, tests/e2e-openshift/monitoring-monolithic/check_metrics.sh, tests/e2e-openshift/monitoring-monolithic/generate-traces-assert.yaml, tests/e2e-openshift/monitoring-monolithic/generate-traces.yaml, tests/e2e-openshift/monitoring-monolithic/install-monolithic-assert.yaml, tests/e2e-openshift/monitoring-monolithic/install-monolithic.yaml, tests/e2e-openshift/monitoring-monolithic/verify-traces.yaml, tests/e2e-openshift/monitoring-monolithic/workload-monitoring-assert.yaml, tests/e2e-openshift/monitoring-monolithic/workload-monitoring.yaml, tests/e2e-openshift/monitoring/chainsaw-test.yaml
Test metrics generated by Tempo Monolithic instance can be scraped by user workload monitoring stack.
=> [Chore] Test metrics produced by Tempo Monolithc

tests/e2e/monolithic-receivers-tls/04-assert.yaml, tests/e2e/monolithic-receivers-tls/04-verify-traces.yaml
Fix the test failing on OCP 4.17. 
```
=== ERROR
pods "verify-traces-http" is forbidden: violates PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "verify-traces" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "verify-traces" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "verify-traces" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "verify-traces" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```
After fix:
```
--- PASS: chainsaw/monolithic-receivers-tls (96.75s)
PASS
- Passed  tests 1
Done.
```
=> [Chore] Fix test monolithic-receivers-tls failing on OCP 4.17

.chloggen/metrics-cleanup.yaml, bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, config/webhook/manifests.yaml, internal/status/metrics.go, internal/status/status.go, internal/webhooks/tempomonolithic_webhook.go, internal/webhooks/tempostack_webhook.go
https://issues.redhat.com/browse/TRACING-4609
Tested with 
```
kubectl apply -f - <<EOF
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
name: simplestmono
spec:
storage:
traces:
backend: s3 
size: 3Gi 
s3: 
secret: minio-test
EOF
kubectl apply -f - <<EOF
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
name: simplest
spec:
storage:
secret:
name: minio-test
type: s3
storageSize: 1Gi
EOF
```
Then port-forward the operator 8080 and check for metric `controller_runtime_reconcile_total`
=> Cleanup operator instance metrics when instance is deleted

tests/e2e-openshift/tls-monolithic-singletenant/01-assert.yaml, tests/e2e-openshift/tls-singletenant/01-assert.yaml, tests/e2e-openshift/tls-singletenant/chainsaw-test.yaml
Fixes tests after fix https://github.com/grafana/tempo-operator/pull/1020 
```
--- PASS: chainsaw/tls-singletenant-monolithic (85.10s)
--- PASS: chainsaw/tls-singletenant (138.27s)
PASS
- Passed  tests 2
Done.
```
=> [Chore] Fix tests after the reconciliation fix

.chloggen/enable-130.yaml, .github/workflows/e2e.yaml, .github/workflows/scorecard.yaml, kind-1.30.yaml
Enabling operator tests to run on Kubernetes 1.30. Referencing the work of https://github.com/grafana/tempo-operator/pull/807.
Closes #1030
=> Kubernetes 1.30 enablement

.chloggen/fix_unknown_flag.yaml, internal/manifests/queryfrontend/query_frontend.go, internal/manifests/queryfrontend/query_frontend_test.go
Since [Jaeger 1.58.0](https://github.com/jaegertracing/jaeger/releases/tag/v1.58.0) this flag no longer exists.
=> Fix: Dont append deprecated span metrics connector flag

tests/e2e-openshift/red-metrics/03-assert.yaml, tests/e2e-openshift/red-metrics/06-assert.yaml, tests/e2e-openshift/red-metrics/06-install-assert-job.yaml, tests/e2e-openshift/red-metrics/check_metrics.sh
The PR fixes the test case to avoid running into issues like https://issues.redhat.com/browse/TRACING-4608 
* The test case was earlier checking only the ClusterRoleBinding with cluster-monitoring-view was attached to the service account used by query frontend. But the test didn't check if the service account is the correct one used by the query frontend deployment. The updated PR ensures that the right service account is created, used by the deployment and has the monitoring view role. 
* Use the tempo-redmetrics-query-frontend SA token to check the metrics from Thanos querier instead of using the prometheus-user-workload-monitoring SA. The query frontend SA has the monitoring view role.
=> [Chore] Fix RED metrics test case to ensure monitorTab can display data

.chloggen/fix_tls_tempo-query.yaml, internal/manifests/queryfrontend/query_frontend.go
Details: https://issues.redhat.com/browse/TRACING-4703
```bash
$ k get pods -n chainsaw-replicas       
NAME                                           READY   STATUS    RESTARTS   AGE
minio-679d9f746b-hngng                         1/1     Running   0          14m
tempo-cmpreps-compactor-bd74cd5c7-mlq2z        1/1     Running   0          6m2s
tempo-cmpreps-distributor-6bc6b5856f-dv92t     1/1     Running   0          6m2s
tempo-cmpreps-gateway-5897b57875-6wltl         2/2     Running   0          6m2s
tempo-cmpreps-ingester-0                       1/1     Running   0          6m2s
tempo-cmpreps-querier-7b74976fd4-d62hd         1/1     Running   0          6m2s
tempo-cmpreps-query-frontend-5558ffd89-5krzk   3/3     Running   0          6m2s
```
=> fix: mount cert and ca to tempo-query

tests/e2e-long-running/tempostack-retention-global/00-assert.yaml, tests/e2e-long-running/tempostack-retention-global/00-install-storage.yaml, tests/e2e-long-running/tempostack-retention-global/01-assert.yaml, tests/e2e-long-running/tempostack-retention-global/01-install.yaml, tests/e2e-long-running/tempostack-retention-global/03-assert.yaml, tests/e2e-long-running/tempostack-retention-global/03-generate-traces.yaml, tests/e2e-long-running/tempostack-retention-global/04-assert.yaml, tests/e2e-long-running/tempostack-retention-global/04-verify-traces-jaeger.yaml, tests/e2e-long-running/tempostack-retention-global/05-assert.yaml, tests/e2e-long-running/tempostack-retention-global/05-verify-traces-grafana.yaml, tests/e2e-long-running/tempostack-retention-global/chainsaw-test.yaml, tests/e2e-long-running/tempostack-retention-global/verify-traces-grafana-ret-assert.yaml, tests/e2e-long-running/tempostack-retention-global/verify-traces-grafana-ret.yaml, tests/e2e-long-running/tempostack-retention-global/verify-traces-jaeger-ret-assert.yaml, tests/e2e-long-running/tempostack-retention-global/verify-traces-jaeger-ret.yaml
The PR adds a long running test for TempoStack retention. 
```
--- PASS: chainsaw/tempostack-retention-global (2860.06s)
PASS
- Passed  tests 1
Done.
```
=> [Chore] Long running test for TempoStack global retention

tests/e2e-openshift/tempo-single-tenant-auth/install-tempo-assert.yaml, tests/e2e-openshift/tempo-single-tenant-auth/install-tempo.yaml, tests/e2e-openshift/tls-singletenant/01-assert.yaml, tests/e2e-openshift/tls-singletenant/01-install-tempo.yaml
The PR fixes tests after https://github.com/grafana/tempo-operator/pull/1038 change and bumps the resource limits as the distribution of resources among the containers in query frontend pod is reduced after resource allocation and enforcing of limits on Tempo Query container.
=> [Chore] Fix asserts and bump resources for tests

internal/manifests/manifestutils/service.go, internal/manifests/queryfrontend/query_frontend.go
Roughly what you had in  mind?
cc @andreasgerstmayr @IshwarKanse
=> manifestutils: configure CA and ServicePKI by name

tests/e2e-openshift/monolithic-route/chainsaw-test.yaml, tests/e2e-openshift/monolithic-route/install-tempo-assert.yaml, tests/e2e-openshift/monolithic-route/install-tempo.yaml, tests/e2e-openshift/route/chainsaw-test.yaml, tests/e2e-openshift/route/install-storage-assert.yaml, tests/e2e-openshift/route/install-storage.yaml, tests/e2e-openshift/route/install-tempo-assert.yaml, tests/e2e-openshift/route/install-tempo.yaml, tests/e2e-openshift/tls-monolithic-singletenant/01-assert.yaml, tests/e2e-openshift/tls-singletenant/01-assert.yaml, tests/e2e-openshift/tls-singletenant/01-install-tempo.yaml
tests/e2e-openshift/route -- Test with custom timeout set to 2m
tests/e2e-openshift/monolithic-route -- Test with custom timeout set to 2m
tests/e2e-openshift/tls-singletenant -- Test default timeout of 30s
tests/e2e-openshift/tls-monolithic-singletenant/ -- Test default timeout of 30s
```
--- PASS: chainsaw/monolithic-route (55.16s)
--- PASS: chainsaw/tls-singletenant-monolithic (96.14s)
--- PASS: chainsaw/route (138.22s)
--- PASS: chainsaw/tls-singletenant (164.25s)
PASS
- Passed  tests 4
Done.
```
Once the multitenancy issues are fixed, will add the asserts for the multitenancy tests as well.
=> [Chore] Test timeout for non-multitenant TempoStack and TempoMonolithic instances.

.chloggen/bump_jaeger-to-1.62.yaml, Makefile, bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, config/manager/manager.yaml
Jaeger 1.62 released. It includes the multi tenancy fix.
https://github.com/jaegertracing/jaeger/releases/tag/v1.62.0
=> jaeger-query: upgrade to version 1.62

.chloggen/fix_jaeger-query-certs.yaml, internal/manifests/queryfrontend/query_frontend.go
=> queryfrontend: grant jaeger-query access to pki certs

tests/e2e-openshift/monolithic-route/chainsaw-test.yaml, tests/e2e-openshift/monolithic-route/check-must-gahter.sh, tests/e2e-openshift/route/chainsaw-test.yaml, tests/e2e-openshift/route/check-must-gahter.sh
```
--- PASS: chainsaw/monolithic-route (73.55s)
--- PASS: chainsaw/route (133.26s)
PASS
- Passed  tests 2
Done.
```
=> [Chore] Test must-gather script

.chloggen/tempo-query_ReadinessProbe.yaml, internal/manifests/queryfrontend/query_frontend.go, internal/manifests/queryfrontend/query_frontend_test.go
Closes #1058
Requieres:
- https://github.com/grafana/tempo/pull/4178
=> tempo-query: add ReadinessProbe

.github/workflows/continuous-integration.yaml, cmd/gather/cluster/cluster.go, cmd/gather/cluster/write.go, cmd/generate/main.go, controllers/tempo/tempostack_controller.go
I had to bump the linter because old version got stuck in the actions. Not sure what changed, but bumping the version seems to work.
=> Bump linter to 1.61.0

internal/manifests/servicemonitor/servicemonitor.go
When the gateway is disabled, the query frontend is not protected by `mTLS`, nor `TLS`. The only case when it is protected is when the gateway is enabled.
Because of that, the SM needs to be created using HTTP instead of HTTPs, 
Same port/endpoint  is used for Tempo API and the metrics. We cannot choose to protect the `/metrics` endpoint without affect the Tempo API.
cc @andreasgerstmayr  WDYT?
Or perhaps  we should take another approach and try to enable only TLS with the internal certs? 
Or `mTLS` and the `oauth-proxy`? not sure if this scenario is supported by `oauth-proxy.`
=> Set HTTP protocol in query-frontend ServiceMonitor

Makefile
The latest OLM version v0.29.0 has an issue https://github.com/operator-framework/operator-lifecycle-manager/issues/3419 affecting pod deployments on KinD clusters causing failures. This PR pins the OLM version to v0.28.0 to fix the failing upgrade test.
=> [Chore] Specify the OLM version to be installed by operator-sdk

tests/e2e-openshift/monitoring/02-assert.yaml, tests/e2e-openshift/monolithic-route/chainsaw-test.yaml, tests/e2e-openshift/monolithic-route/check-must-gather.sh, tests/e2e-openshift/route/chainsaw-test.yaml, tests/e2e-openshift/route/check-must-gather.sh, tests/e2e-openshift/tempo-single-tenant-auth/install-tempo-assert.yaml, tests/e2e-openshift/tls-singletenant/01-assert.yaml
Fix the asserts for tests after the latest commits.
=> [Chore] Fix e2e tests

.chloggen/internal_tracing.yaml, internal/manifests/gateway/gateway.go, internal/manifests/gateway/gateway_test.go
The opa-openshift container does not support
`--internal.tracing.endpoint` and remains in a crashloop if
```
spec:
observability:
tracing:
jaeger_agent_endpoint: ...
sampling_fraction: "1"
```
is enabled.
=> Do not add tracing CLI args to opa-openshift container

.github/workflows/changelog.yaml
`markdown-link-check` started to fail on valid markdown files. See https://github.com/tcort/markdown-link-check/issues/369
=> Pin markdown-link-check to latest working version

tests/e2e-openshift/tempostack-resources/install-tempostack-assert.yaml
```
--- PASS: chainsaw (1937.38s)
--- PASS: chainsaw/ossm-monolithic-otel (322.95s)
--- PASS: chainsaw/ossm-tempostack (313.32s)
--- PASS: chainsaw/ossm-tempostack-otel (323.29s)
--- PASS: chainsaw/otel-tempo-serverless (298.29s)
--- PASS: chainsaw/tempo-serverless (263.62s)
--- PASS: chainsaw/monitoring (147.31s)
--- PASS: chainsaw/monolithic-monitoring (84.44s)
--- PASS: chainsaw/red-metrics (184.16s)
--- PASS: chainsaw/operator-metrics (22.76s)
--- PASS: chainsaw/tls-singletenant-monolithic (111.04s)
--- PASS: chainsaw/reconcile (115.99s)
--- PASS: chainsaw/tempostack-extraconfig (118.51s)
--- PASS: chainsaw/receivers-tls (147.27s)
--- PASS: chainsaw/compatibility (151.26s)
--- PASS: chainsaw/tls-singletenant (153.65s)
--- PASS: chainsaw/receivers-mtls (138.32s)
--- PASS: …
```
=> [Chore] Fix tempostack-resources test case

tests/e2e-upgrade/upgrade/20-assert.yaml
The kube-rbac-proxy got removed.
=> fix upgrade e2e test

tests/e2e-openshift-ossm/ossm-monolithic-otel/install-ossm-assert.yaml, tests/e2e-openshift-ossm/ossm-monolithic-otel/update-kiali.yaml, tests/e2e-openshift-ossm/ossm-tempostack-otel/install-ossm-assert.yaml, tests/e2e-openshift-ossm/ossm-tempostack-otel/update-kiali.yaml, tests/e2e-openshift-ossm/ossm-tempostack/install-ossm-assert.yaml, tests/e2e-openshift-ossm/ossm-tempostack/update-kiali.yaml
The PR resolves issue with Kiali not starting up due to bug https://github.com/kiali/kiali/issues/8071 
```
--- PASS: chainsaw (1012.27s)
--- PASS: chainsaw/ossm-monolithic-otel (303.90s)
--- PASS: chainsaw/ossm-tempostack (332.82s)
--- PASS: chainsaw/ossm-tempostack-otel (375.56s)
PASS
- Passed  tests 3
Done.
```
=> [Chore] Update tests to resolve OSSM Kiali issue

bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, cmd/start/main.go, config/overlays/openshift/patch_tls_metrics_args.yaml
`CertName` and `KeyName` are only the name of the files, we also need to specify the full path in which those files exists. This PR fix that.
When the certificate file doesn't exist it will self-sign one with _localhost_. Because the path were wrong, it always generate the self signed.
This PR also add a cert-dir flag to specify the path
=> Fix metrics TLS certificate parameters

.chloggen/fix-overrides.yaml, internal/manifests/config/build.go, internal/manifests/config/build_test.go, internal/manifests/config/options.go, internal/manifests/config/tempo-overrides.yaml, tests/e2e-openshift/multitenancy/01-install-tempo.yaml
We forgot to adapt to a breaking change in Tempo 2.3 https://github.com/grafana/tempo/blob/main/CHANGELOG.md#v230--2023-10-30 
Adds support for tenant retention overrides https://issues.redhat.com/browse/TRACING-5120 
https://grafana.com/docs/tempo/v2.0.x/configuration/#overrides
https://grafana.com/docs/tempo/v2.7.x/configuration/
=> Add support for renant retention overrides and fix limit overrides after tempo 2.3

.chloggen/gcs_short_live_token.yaml, internal/handlers/storage/secret.go, internal/handlers/storage/secret_test.go, internal/manifests/manifestutils/annotations.go, internal/manifests/manifestutils/annotations_test.go, internal/manifests/manifestutils/params.go, internal/manifests/manifestutils/storage.go, internal/manifests/manifestutils/storage_test.go, internal/manifests/monolithic/configmap.go, internal/manifests/monolithic/serviceaccount.go, internal/manifests/monolithic/statefulset.go, internal/manifests/oauthproxy/oauth_proxy.go, internal/manifests/serviceaccount/serviceaccount.go
=> Add support for GCS short live token

.chloggen/ensure_permissions.yaml, internal/webhooks/tempomonolithic_webhook.go, internal/webhooks/tempomonolithic_webhook_test.go, internal/webhooks/tempostack_webhook.go, internal/webhooks/tempostack_webhook_test.go, internal/webhooks/validations.go
Ensure the permissions the operator is granting to the Tempo Service Account do not exceed the permissions of the user creating (or modifying) the Tempo instance when enabling OpenShift tenancy mode.
To enable the OpenShift tenancy mode, the user must have permissions to create `TokenReview` and `SubjectAccessReview`.
Resolves CVE-2025-2786
=> Fix CVE-2025-2786: Ensure the operator does not grant additional permissions when enabling OpenShift tenancy mode

.github/workflows/changelog.yaml, .github/workflows/continuous-integration.yaml, .github/workflows/e2e.yaml, .github/workflows/olm.yaml, .github/workflows/prepare-release.yaml, .github/workflows/publish-images.yaml, .github/workflows/publish-test-utils-image.yaml, .github/workflows/release.yaml, .github/workflows/reusable-operator-hub-release.yaml, .github/workflows/reusable-publish-images.yaml, .github/workflows/scorecard.yaml
changed based on audit using zizmor: https://woodruffw.github.io/zizmor/audits/
see more: https://grafana.com/blog/2025/04/27/grafana-security-update-no-customer-impact-from-github-workflow-vulnerability/
=> Harden CI: resolve zizmor alerts

.chloggen/clusterscope_label.yaml, internal/controller/tempo/tempomonolithic_controller.go, internal/controller/tempo/tempostack_create_or_update.go, internal/manifests/gateway/gateway.go, internal/manifests/manifestutils/labels.go, internal/manifests/monolithic/gateway.go, internal/manifests/monolithic/gateway_test.go, internal/manifests/monolithic/labels.go, tests/e2e-openshift/monolithic-multitenancy-openshift/01-assert.yaml, tests/e2e-openshift/multitenancy/01-assert.yaml
This PR adds a `app.kubernetes.io/namespace` label to cluster-scoped resources, to filter them by the pruning code.
See https://issues.redhat.com/browse/TRACING-5355.
Alternatively, we could
* add this label to all components
* add the namespace to the instance label (OTEL operator does that: https://github.com/open-telemetry/opentelemetry-operator/blob/02e42e5db45616e982343a87cc6519df1c21578c/internal/manifests/manifestutils/labels.go#L71)
However, both alternatives would change the immutable `selector` field of the `Deployment` and `StatefulSet` resources, requiring to delete and recreate all Deployments and StatefulSets.
=> Fix pruning of cluster-scoped resources

.chloggen/fix-cluster-admin-filtering.yaml, internal/manifests/gateway/openshift.go, internal/manifests/gateway/openshift_test.go, internal/manifests/monolithic/statefulset_test.go, tests/e2e-openshift/component-replicas/install-tempo-assert.yaml, tests/e2e-openshift/component-replicas/scale-tempo-assert.yaml, tests/e2e-openshift/multitenancy-rbac/01-assert.yaml, tests/e2e-openshift/multitenancy/01-assert.yaml
Resolves https://issues.redhat.com/browse/TRACING-5354
=> RBAC: allow cluster admins to see all attributes

.github/workflows/publish-images.yaml, .github/workflows/release.yaml, .github/workflows/reusable-publish-images.yaml
Looks like the permissions have to be set on the reusable workflow instead of the workflow which triggers the reusable workflow.
Follow-up from #1184
=> [chore] Move image push permissions to reusable-publish-images workflow

.github/workflows/changelog.yaml, .github/workflows/publish-images.yaml, .github/workflows/publish-test-utils-image.yaml, .github/workflows/release.yaml, .github/workflows/reusable-publish-images.yaml
Both the "root" workflow and the reusable workflow have to have the permissions set. Additionally, I moved the permissions on the job level instead of the root level (which would apply to all jobs).
=> [chore] add permissions on job level

.github/workflows/prepare-release.yaml, .github/workflows/reusable-operator-hub-release.yaml
In this PR https://github.com/grafana/tempo-operator/pull/1169 `persist-credentials ` is set to false, but we need it because this flow executes a git push operation on the bot repository.
According to this documentation https://docs.zizmor.sh/audits/#remediation should be set explicity to false, unless needed for git operations. Which is the case for this github action flow.
Same case for reusable-operator-hub-release flow
=> Explicit add persist-credentials=true for release flows

.chloggen/remove_deprecated_cache_settting.yaml, internal/manifests/config/build_test.go, internal/manifests/config/tempo-config.yaml, tests/e2e-openshift/route/install-tempo-assert.yaml, tests/e2e-openshift/tls-singletenant/01-assert.yaml, tests/e2e/tempostack-extraconfig/install-tempostack-assert.yaml
Resolves #1136
cc @rubenvp8510 do you remember why we had `cache: none` in the config? I'd assume that's the default setting anyway?
=> Remove deprecated storage.trace.cache setting

bundle/community/manifests/tempo-operator-manager-config_v1_configmap.yaml, config/overlays/community/controller_manager_config.yaml, internal/manifests/networking/policies.go, internal/manifests/operator/manifests.go, tests/e2e/networking/00-asserts.yaml, tests/e2e/networking/chainsaw-test.yaml
Since we did not release, I assume we can skip the changelog?
=> enable operator network policies on all OpenShift/k8s versions by default

internal/manifests/networking/operator.go, internal/manifests/networking/policies.go, tests/e2e/networking/00-asserts.yaml
Only needed for the operands. The Operator seems to work fine without DNS.
Updates #1250 
cc @IshwarKanse
=> remove operator's dns network policy
