.github/workflows/continuous-integration.yaml, Makefile
Signed-off-by: Israel Blancas <iblancasa@gmail.com>
Add CI for the operator.
Closes #2
=> Add CI to the operator

api/v1alpha1/microservices_types.go
=> api: add API/CRD description

.github/workflows/publish-images.yaml
Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>
Closes #5
=> Publish operator image to GHCR

.github/workflows/continuous-integration.yaml, .golangci.yaml, Makefile, api/v1alpha1/groupversion_info.go, api/v1alpha1/microservices_types.go, controllers/microservices_controller.go
Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>
Fixes #8 
cc @iblancasa
=> configure golang-ci

.github/workflows/publish-images.yaml
Signed-off-by: Israel Blancas <iblancasa@gmail.com>
Resolves #17
=> Avoid fast cache growing in GitHub Actions Workflow Cache

.github/workflows/publish-images.yaml
Signed-off-by: Israel Blancas <iblancasa@gmail.com>
Fixes #20
=> Fixes broken build image in GitHub Actions

README.md
=> Add basic information to readme

Makefile, docs/api.md
the next part will ensure that docs are up-to-date.
=> Support crdoc generation #7

Makefile
Signed-off-by: Kevin Earls <kearls@redhat.com>
=> Remove duplicate operator-sdk target

bundle/manifests/tempo-operator-webhook-service_v1_service.yaml, bundle/manifests/tempo-operator.clusterserviceversion.yaml, config/default/kustomization.yaml
=> fix: cert manager CA injection

Makefile
This is needed for webhooks that the operator uses
=> Add cert-manager install target to makefile

README.md, bundle/manifests/tempo-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/rbac/role.yaml, controllers/microservices_controller.go, controllers/microservices_controller_test.go, go.sum, internal/manifests/config/configmap.go, internal/manifests/config/configmap_test.go, internal/manifests/distributor/distributor.go, internal/manifests/ingester/ingester.go, internal/manifests/ingester/ingester_test.go, internal/manifests/manifests.go, internal/manifests/manifestutils/storage.go, minio.yaml
=> Use object storage backend

internal/manifests/config/configmap.go, internal/manifests/config/configmap_test.go, internal/manifests/distributor/distributor.go, internal/manifests/distributor/distributor_test.go, internal/manifests/ingester/ingester.go, internal/manifests/ingester/ingester_test.go, internal/manifests/manifests.go, internal/manifests/manifests_test.go, internal/manifests/memberlist/gossip.go
=> Add memberlist gossip service

internal/manifests/distributor/distributor.go, internal/manifests/distributor/distributor_test.go, internal/manifests/ingester/ingester.go, internal/manifests/ingester/ingester_test.go, internal/manifests/memberlist/gossip_test.go
=> Add labels to services

Makefile
=> Fix generated deepcopy file changes check

README.md, apis/tempo/v1alpha1/microservices_types.go
=> Enable jaeger-query in example CR and allow empty per tenant config

README.md
=> Add development build and deploy instructions

internal/manifests/compactor/compactor.go, internal/manifests/compactor/compactor_test.go, internal/manifests/manifests.go, internal/manifests/manifests_test.go
~This change needs a final test again. Broke my local test setup yesterday...~
=> Support compactor

apis/tempo/v1alpha1/microservices_types.go, apis/tempo/v1alpha1/microservices_webhook.go, apis/tempo/v1alpha1/microservices_webhook_test.go, bundle/manifests/tempo-operator.clusterserviceversion.yaml, bundle/manifests/tempo.grafana.com_microservices.yaml, config/crd/bases/tempo.grafana.com_microservices.yaml, config/manifests/bases/tempo-operator.clusterserviceversion.yaml, docs/api.md, internal/manifests/config/configmap.go, internal/manifests/config/configmap_test.go
=> support global block retention

README.md
Signed-off-by: Kevin Earls <kearls@redhat.com>
=> Fix the namespace name in the README

internal/manifests/compactor/compactor.go, internal/manifests/compactor/compactor_test.go, internal/manifests/distributor/distributor.go, internal/manifests/distributor/distributor_test.go, internal/manifests/ingester/ingester.go, internal/manifests/ingester/ingester_test.go, internal/manifests/querier/querier.go, internal/manifests/querier/querier_test.go, internal/manifests/queryfrontend/query_frontend.go, internal/manifests/queryfrontend/query_frontend_test.go
Closes https://github.com/os-observability/tempo-operator/issues/66
=> respect nodeselector and tolerations settings

apis/tempo/v1alpha1/microservices_types.go, bundle/manifests/tempo-operator.clusterserviceversion.yaml, bundle/manifests/tempo.grafana.com_microservices.yaml, config/crd/bases/tempo.grafana.com_microservices.yaml, config/manifests/bases/tempo-operator.clusterserviceversion.yaml, docs/api.md
=> Mark storage.secret required in the CRD

controllers/tempo/microservices_controller.go, tests/e2e/reconcile/00-assert.yaml, tests/e2e/reconcile/00-install-minio.yaml, tests/e2e/reconcile/01-assert.yaml, tests/e2e/reconcile/01-install.yaml, tests/e2e/reconcile/02-assert.yaml, tests/e2e/reconcile/02-delete-svc.yaml
The controller needs to own its generated resources and reconcile if any resource changes or gets deleted.
Resolves: #138
=> Own generated resources

internal/manifests/compactor/compactor.go, internal/manifests/compactor/compactor_test.go, internal/manifests/distributor/distributor.go, internal/manifests/distributor/distributor_test.go, internal/manifests/ingester/ingester.go, internal/manifests/ingester/ingester_test.go, internal/manifests/manifestutils/constants.go, internal/manifests/memberlist/gossip.go, internal/manifests/memberlist/gossip_test.go, internal/manifests/querier/querier.go, internal/manifests/querier/querier_test.go, internal/manifests/queryfrontend/query_frontend.go, internal/manifests/queryfrontend/query_frontend_test.go, tests/e2e/reconcile/01-assert.yaml, tests/e2e/reconcile/02-assert.yaml, tests/e2e/smoketest-with-jaeger/01-assert.yaml
=> Move manifest constants to shared file

apis/tempo/v1alpha1/microservices_types.go, bundle/manifests/tempo.grafana.com_microservices.yaml, config/crd/bases/tempo.grafana.com_microservices.yaml, controllers/tempo/microservices_controller.go, controllers/tempo/microservices_controller_test.go, docs/api.md, go.mod, go.sum
=> Add version and age status fields

apis/tempo/v1alpha1/microservices_types.go, bundle/manifests/tempo-operator.clusterserviceversion.yaml, bundle/manifests/tempo.grafana.com_microservices.yaml, config/crd/bases/tempo.grafana.com_microservices.yaml, config/manifests/bases/tempo-operator.clusterserviceversion.yaml, docs/api.md
Please check if the fields are really implemented.
=> Remove not implemented notes from API package

cmd/generate/main.go, cmd/generate/main_test.go
I forgot to rebase #168 after merging #158 into main.
=> Update import path of Params

internal/manifests/queryfrontend/query_frontend.go, internal/manifests/queryfrontend/query_frontend_test.go, tests/e2e/smoketest-with-jaeger/01-assert.yaml
=> Make query-frontend-discovery service headless

internal/manifests/compactor/compactor.go, internal/manifests/compactor/compactor_test.go, internal/manifests/distributor/distributor.go, internal/manifests/distributor/distributor_test.go, internal/manifests/ingester/ingester.go, internal/manifests/ingester/ingester_test.go, internal/manifests/manifestutils/constants.go, internal/manifests/manifestutils/probes.go, internal/manifests/querier/querier.go, internal/manifests/querier/querier_test.go, internal/manifests/queryfrontend/query_frontend.go, internal/manifests/queryfrontend/query_frontend_test.go, tests/e2e/reconcile/01-install.yaml, tests/e2e/smoketest-with-jaeger/01-install.yaml
=> Configure readiness probes

.golangci.yaml
=> golangci: disable fieldalignment check

internal/manifests/memberlist/gossip.go, internal/manifests/memberlist/gossip_test.go, tests/e2e/smoketest-with-jaeger/01-assert.yaml
Resolves: #150
Ref. https://github.com/grafana/tempo/issues/771
=> Make gossip-ring service headless

apis/tempo/v1alpha1/microservices_types.go, apis/tempo/v1alpha1/microservices_webhook.go, apis/tempo/v1alpha1/microservices_webhook_test.go, bundle/manifests/tempo-operator-manager-config_v1_configmap.yaml, bundle/manifests/tempo-operator.clusterserviceversion.yaml, cmd/generate/main_test.go, cmd/start/main.go, config/manager/controller_manager_config.yaml, config/manifests/bases/tempo-operator.clusterserviceversion.yaml, internal/manifests/gateway/build.go, internal/manifests/gateway/gateway-rbac.yaml, internal/manifests/gateway/gateway-tenants.yaml, internal/manifests/gateway/tempo-gateway.rego, internal/manifests/gateway/testdata/rbac.yaml, internal/manifests/gateway/testdata/tenants.yaml, internal/manifests/manifests.go, internal/manifests/manifests_test.go, internal/version/main.go
WIP: split commits
Still some work to do. I wouldnt recommend to enable the gateway. :x: 
**update**
removed e2e tests
=> gateway: support tempo gateway

apis/tempo/v1alpha1/microservices_types.go, bundle/manifests/tempo-operator-manager-config_v1_configmap.yaml, bundle/manifests/tempo.grafana.com_microservices.yaml, config/crd/bases/tempo.grafana.com_microservices.yaml, config/manager/controller_manager_config.yaml, docs/api.md
=> Make OIDC optional and use upstream images

internal/manifests/gateway/build.go
=> Use bytebuffer reset for generating gateway configs

internal/manifests/mutate.go, internal/manifests/mutate_test.go
=> support mutating secerts

internal/manifests/gateway/build.go
=> fix: address of trace endpoint in gateway

.golangci.yaml, apis/tempo/v1alpha1/microservices_types.go, apis/tempo/v1alpha1/microservices_webhook.go, apis/tempo/v1alpha1/webhook_suite_test.go, cmd/generate/main.go, cmd/root.go, cmd/start/main.go, cmd/version/main.go, controllers/tempo/microservices_controller.go, internal/manifests/manifestutils/annotations.go, internal/manifests/manifestutils/constants.go, internal/manifests/manifestutils/labels.go, internal/manifests/manifestutils/resources.go, internal/manifests/manifestutils/securitycontext.go, internal/manifests/memberlist/gossip.go, internal/manifests/serviceaccount/serviceaccount.go, internal/status/client.go, internal/status/status.go
=> Enforce godoc for exported types and functions

.github/workflows/publish-images.yaml
This will need an update after #190 is merged.
=> Publish bundle and catalog on GitHub Container Registry

bundle/manifests/tempo-operator.clusterserviceversion.yaml, cmd/root.go, config/rbac/role.yaml, controllers/tempo/microservices_controller.go, internal/manifests/gateway/configs_test.go, internal/manifests/gateway/gateway-tenants.yaml, internal/manifests/gateway/gateway.go, internal/manifests/manifests_test.go, internal/manifests/manifestutils/constants.go
Resolves https://github.com/os-observability/tempo-operator/issues/243 and other small issues as well (RBAC for route, OCP oauth redirect URL)
=> Fix RBAC and route issues in gateway

bundle/manifests/tempo-operator.clusterserviceversion.yaml, config/manager/manager.yaml
Might re-evaluate later with appropriate limits (the current ones are too small for some clusters).
=> Drop operator resource limits for now

apis/tempo/v1alpha1/tempostack_webhook.go, apis/tempo/v1alpha1/tempostack_webhook_test.go, internal/manifests/queryfrontend/query_frontend.go
=> Avoid creation of query frontend route if gateway is enabled

config/samples/tempo_v1alpha1_openshift.yaml, internal/manifests/gateway/gateway.go
=> Fix error log related to gateway deployment and fix OCP example

internal/manifests/gateway/gateway.go, internal/manifests/gateway/gateway_test.go, internal/manifests/gateway/openshift.go, internal/manifests/gateway/openshift_test.go
=> Enable back gateway probes

Makefile
Fixes https://github.com/os-observability/tempo-operator/issues/355
=> Fix Makefile bundle rule

Makefile
=> [chore] update bundle-build rule to take into account different bundles

apis/config/v1alpha1/projectconfig_types.go, bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo-operator-manager-config_v1_configmap.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, config/overlays/openshift/config/controller_manager_config.yaml, docs/operator/feature-gates.md, internal/manifests/gateway/gateway.go, internal/manifests/gateway/gateway_test.go
=> Remove operator gateway OCP route feature gate

apis/config/v1alpha1/projectconfig_types.go, apis/tempo/v1alpha1/tempostack_webhook.go, apis/tempo/v1alpha1/tempostack_webhook_test.go, bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, cmd/root.go, config/rbac/role.yaml, controllers/tempo/tempostack_controller.go, controllers/tempo/tempostack_controller_test.go, docs/operator/feature-gates.md, internal/manifests/compactor/compactor.go, internal/manifests/config/build.go, internal/manifests/config/var.go, internal/manifests/distributor/distributor.go, internal/manifests/gateway/gateway.go, internal/manifests/ingester/ingester.go, internal/manifests/manifests.go, internal/manifests/manifestutils/service.go, internal/manifests/mutate.go, internal/manifests/mutate_test.go, internal/manifests/naming/naming.go, internal/manifests/naming/naming_test.go, internal/manifests/querier/querier.go, internal/manifests/queryfrontend/query_frontend.go, internal/manifests/queryfrontend/query_frontend_test.go, internal/manifests/servicemonitor/servicemonitor.go, internal/manifests/servicemonitor/servicemonitor_test.go, tests/e2e/smoketest-with-jaeger/01-assert.yaml
=> Create ServiceMonitors for all components

.chloggen/sanitize_names.yaml, apis/tempo/v1alpha1/tempostack_webhook.go, apis/tempo/v1alpha1/tempostack_webhook_test.go, internal/manifests/naming/naming.go, internal/manifests/naming/sanitize.go, internal/manifests/naming/sanitize_test.go
Fixes https://github.com/os-observability/tempo-operator/issues/233
=> Add sanitization to names and validate length of tempoStack name

apis/config/v1alpha1/projectconfig_types.go, docs/operator/feature-gates.md
=> Improve mTLS gate flags documentation

.chloggen/configure_logging.yaml, main.go, main_test.go
Afaics it was removed in #303 by mistake.
=> Re-add logging setup

Makefile, RELEASE.md
Update release instructions with commands for testing upgrades with OLM.
=> Update release instructions

tests/e2e/gateway/00-assert.yaml, tests/e2e/gateway/02-assert.yaml
Should fix flaky behavior of this test.
=> Assert readyness for gateway deployment in e2e test

.chloggen/expose_more_protocols.yaml, internal/manifests/config/build_test.go, internal/manifests/config/tempo-config.yaml, internal/manifests/distributor/distributor.go, internal/manifests/distributor/distributor_test.go, internal/manifests/manifestutils/constants.go, tests/e2e/generate/01-assert.yaml, tests/e2e/smoketest-with-jaeger/01-assert.yaml
=> Expose more protocols

.github/workflows/changelog.yaml, .github/workflows/continuous-integration.yaml, .github/workflows/e2e.yaml, .github/workflows/publish-images.yaml, .github/workflows/release.yaml, .github/workflows/scorecard.yaml
* should fix flaky scorecard test, I couldn't reproduce it anymore with 22.04
* run scorecard tests of all bundles
Resolves: #380
=> Update Github Actions VMs to Ubuntu 22.04 LTS

.chloggen/uniform_logging.yaml, apis/tempo/v1alpha1/tempostack_webhook.go, cmd/generate/main.go, controllers/tempo/certrotation_controller.go, controllers/tempo/tempostack_controller.go, go.mod, internal/logging/logging.go, internal/logging/logging_test.go, main.go, main_test.go
Resolves: https://github.com/grafana/tempo-operator/issues/430
=> Use consistent log format, specify logger names and update log severity levels of reconcile logs

README.md, apis/tempo/v1alpha1/tempostack_types.go, bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/community/manifests/tempo.grafana.com_tempostacks.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo.grafana.com_tempostacks.yaml, config/crd/bases/tempo.grafana.com_tempostacks.yaml, config/manifests/community/bases/tempo-operator.clusterserviceversion.yaml, config/manifests/openshift/bases/tempo-operator.clusterserviceversion.yaml, docs/operator/api.md
* add metadata.annotations.description 1-liner description
* list operator features in the spec.description field
* add link to spec.description where to find more information about tempo
* add pre-requisites for using the operator in the description field (object storage)
* "TempoStack is the Schema for the tempostacks API." -> "TempoStack is the spec for Tempo deployments."
* update "provided by": "Grafana Tempo SIG Operator"
* change support field from "Tempo Operator SIG" to "Grafana Tempo SIG Operator"
* update keywords
Resolves: #444
=> Update CSV metadata

.chloggen/upgrade.yaml, CONTRIBUTING.md, RELEASE.md, apis/tempo/v1alpha1/tempostack_types.go, apis/tempo/v1alpha1/tempostack_webhook.go, bundle/community/manifests/tempo.grafana.com_tempostacks.yaml, bundle/openshift/manifests/tempo.grafana.com_tempostacks.yaml, cmd/start/main.go, config/crd/bases/tempo.grafana.com_tempostacks.yaml, docs/operator/api.md, go.mod, go.sum, internal/status/status.go, internal/status/status_test.go, internal/upgrade/suite_test.go, internal/upgrade/upgrade.go, internal/upgrade/upgrade_test.go, internal/upgrade/v0_1_0.go, internal/upgrade/versions.go
=> Implement operator upgrade

Dockerfile, Makefile
Resolves https://github.com/openshift/release/pull/40691#issuecomment-1609849559
=> Remove api-docs generation from build

.chloggen/multitenant_nogw.yaml, apis/tempo/v1alpha1/tempostack_webhook.go, apis/tempo/v1alpha1/tempostack_webhook_test.go, internal/manifests/gateway/gateway.go, internal/manifests/manifests.go
Fixes https://github.com/grafana/tempo-operator/issues/224
=> Add ability to enable multitenancy without gateway

controllers/tempo/tempostack_controller.go, controllers/tempo/tempostack_controller_test.go, controllers/tempo/tempostack_create_or_update.go
No code change, only restructuring the reconcile loop by moving functions to a new file.
=> Move reconcileManifests() to tempostack_create_or_update.go

internal/status/status.go, internal/upgrade/upgrade.go
=> Add tempooperator_failed_upgrades_total metric

.chloggen/level4.yaml, bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, config/manifests/community/bases/tempo-operator.clusterserviceversion.yaml, config/manifests/openshift/bases/tempo-operator.clusterserviceversion.yaml
https://sdk.operatorframework.io/docs/overview/operator-capabilities/#level-4---deep-insights
=> Bump operator to Level 4 - Deep Insights

.github/workflows/scorecard.yaml
=> Use podman in scorecard tests

.chloggen/operator_alerts.yaml, bundle/openshift/manifests/tempo-operator-controller-manager-prometheus-rule_monitoring.coreos.com_v1_prometheusrule.yaml, config/prometheus/kustomization.yaml, config/prometheus/rules.yaml, operations/runbook.md
Currently includes three alerts:
* TempoStackUnhealthy
* TempoOperatorReconcileError
* TempoOperatorReconcileDurationHigh
Resolves: #309
=> Add operator alerts and runbook

.chloggen/fix_unsupported_mode.yaml, apis/tempo/v1alpha1/auth.go, bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, config/manifests/community/bases/tempo-operator.clusterserviceversion.yaml, config/manifests/openshift/bases/tempo-operator.clusterserviceversion.yaml
closes #556 
Any idea how to create a good test case for it?
=> fix: provide correct mode name via operator-sdk annotation for oc console

.chloggen/tempo22.yaml, bundle/community/manifests/tempo-operator-manager-config_v1_configmap.yaml, bundle/openshift/manifests/tempo-operator-manager-config_v1_configmap.yaml, config/overlays/community/controller_manager_config.yaml, config/overlays/openshift/controller_manager_config.yaml
Resolves #525 
Release notes https://github.com/grafana/tempo/releases
Blocked by:
=> Upgrade to Tempo 2.2.1

cmd/generate/main.go, controllers/tempo/storage.go, controllers/tempo/storage_test.go, controllers/tempo/tempostack_create_or_update.go, internal/manifests/config/build.go, internal/manifests/config/build_test.go, internal/manifests/config/configmap.go, internal/manifests/config/configmap_test.go, internal/manifests/config/options.go, internal/manifests/config/tempo-config.yaml, internal/manifests/manifests.go, internal/manifests/manifestutils/params.go
* unifies all storage structs in `manifestutils.StorageParams`
* removes `config.Params` in favor of `manifestutils.Params`
Resolves: #314
Resolves: #409
=> Cleanup duplicate storage structs

bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, config/manifests/community/bases/tempo-operator.clusterserviceversion.yaml, config/manifests/openshift/bases/tempo-operator.clusterserviceversion.yaml
Docs:
- https://github.com/k8s-operatorhub/community-operators/blob/main/categories.json
- https://github.com/operator-framework/community-operators/blob/master/docs/packaging-required-fields.md#categories
=> Add monitoring OLM category

.chloggen/fix-cve-2023-39325.yaml, bundle/community/manifests/tempo-operator-manager-config_v1_configmap.yaml, bundle/openshift/manifests/tempo-operator-manager-config_v1_configmap.yaml, config/overlays/community/controller_manager_config.yaml, config/overlays/openshift/controller_manager_config.yaml
=> Bump operands to fix CVE-2023-39325

.chloggen/upgrade_tempo_to_v2.3.0.yaml, bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, config/manager/manager.yaml
=> Upgrade tempo to v2.3.0

.github/workflows/release.yaml
Trigger release workflow only for merged PRs changing the CHANGELOG.md file
=> Trigger release workflow only for merged PRs changing the CHANGELOG.md file

.chloggen/proxy_envs.yaml, go.mod, go.sum, internal/manifests/compactor/compactor.go, internal/manifests/compactor/compactor_test.go, internal/manifests/distributor/distributor.go, internal/manifests/distributor/distributor_test.go, internal/manifests/gateway/gateway.go, internal/manifests/ingester/ingester.go, internal/manifests/querier/querier.go, internal/manifests/querier/querier_test.go, internal/manifests/queryfrontend/query_frontend.go, internal/manifests/queryfrontend/query_frontend_test.go
Fixes https://github.com/grafana/tempo-operator/issues/700
=> Add proxy env vars to all containers

.chloggen/replicas.yaml, apis/tempo/v1alpha1/tempostack_types.go, apis/tempo/v1alpha1/tempostack_webhook.go, apis/tempo/v1alpha1/tempostack_webhook_test.go, bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/community/manifests/tempo.grafana.com_tempostacks.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo.grafana.com_tempostacks.yaml, config/crd/bases/tempo.grafana.com_tempostacks.yaml, config/manifests/community/bases/tempo-operator.clusterserviceversion.yaml, config/manifests/openshift/bases/tempo-operator.clusterserviceversion.yaml, docs/operator/api.md, internal/manifests/compactor/compactor.go, internal/manifests/compactor/compactor_test.go, internal/manifests/querier/querier.go, internal/manifests/querier/querier_test.go, internal/manifests/queryfrontend/query_frontend.go, internal/manifests/queryfrontend/query_frontend_test.go
Configure the number of replicas for compactor, querier and query-frontend according to the CR
=> Configure the number of replicas for compactor, querier and query-frontend according to the CR

.chloggen/upgrade_tempo_to_v2.3.1.yaml, bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, config/manager/manager.yaml
=> Upgrade tempo to v2.3.1

Makefile, bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, cmd/start/main.go, config/manifests/community/bases/tempo-operator.clusterserviceversion.yaml, config/manifests/openshift/bases/tempo-operator.clusterserviceversion.yaml, internal/upgrade/upgrade.go
Centralize image locations and versions in makefile, support make run
=> Centralize image locations and versions in makefile, support make run

CONTRIBUTING.md
Update version handling in CONTRIBUTING.md
=> Update version handling in CONTRIBUTING.md

RELEASE.md
=> Add release manager schedule

controllers/tempo/common.go, controllers/tempo/tempomonolithic_controller.go, controllers/tempo/tempostack_create_or_update.go, internal/handlers/storage/storage.go
=> Move listFieldErrors() to controller pkg

.chloggen/fix_oidc_nil.yaml, internal/webhooks/tempostack_webhook.go, internal/webhooks/tempostack_webhook_test.go
Fixes https://github.com/grafana/tempo-operator/issues/647
=> Fix nil pointer when OIDC is not specified in static mode

Makefile
Generate bundle before api-docs
=> Generate bundle before api-docs

bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, config/samples/community/tempo_v1alpha1_tempomonolithic.yaml, config/samples/openshift/tempo_v1alpha1_tempomonolithic.yaml
Set resources in sample TempoMonolithic CR
=> Set resources in sample TempoMonolithic CR

.github/workflows/prepare-release.yaml, .github/workflows/publish-test-utils-image.yaml
Fix prepare-release and publish-test-utils-image workflow on forks
=> Fix prepare-release and publish-test-utils-image workflow on forks

cmd/root.go, controllers/tempo/tempomonolithic_controller.go, controllers/tempo/tempostack_create_or_update.go, go.mod, go.sum, internal/manifests/grafana/datasource.go, internal/manifests/grafana/datasource_test.go, internal/manifests/manifestutils/constants.go, internal/manifests/monolithic/configmap.go, internal/manifests/monolithic/ingress.go, internal/manifests/monolithic/ingress_test.go, internal/manifests/monolithic/labels.go, internal/manifests/monolithic/service.go, internal/manifests/monolithic/service_test.go, internal/manifests/monolithic/statefulset.go, internal/manifests/monolithic/statefulset_test.go, internal/manifests/mutate.go, internal/manifests/naming/naming.go, internal/manifests/servicemonitor/servicemonitor.go, internal/manifests/servicemonitor/servicemonitor_test.go
* add app.kubernetes.io/component label to monolithic objects
* also update Grafana operator package
* specify TypeMeta in ServiceMonitor
=> [chore] add app.kubernetes.io/component label to monolithic objects

internal/status/monolithic.go, internal/status/monolithic_test.go
fix label selector in monolithic status field
=> fix label selector in monolithic status field

cmd/start/main.go, internal/webhooks/tempomonolithic_webhook.go, internal/webhooks/tempomonolithic_webhook_test.go, internal/webhooks/tempostack_webhook.go, internal/webhooks/tempostack_webhook_test.go, internal/webhooks/validations.go
Extend TempoMonolithic validations
=> Extend TempoMonolithic validations

apis/tempo/v1alpha1/auth.go, bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/community/manifests/tempo.grafana.com_tempostacks.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo.grafana.com_tempostacks.yaml, config/crd/bases/tempo.grafana.com_tempostacks.yaml, config/manifests/community/bases/tempo-operator.clusterserviceversion.yaml, config/manifests/openshift/bases/tempo-operator.clusterserviceversion.yaml, docs/operator/api.md, docs/spec/tempo.grafana.com_tempostacks.yaml
Update tenantName and tenantId descriptions
=> Update tenantName and tenantId descriptions

internal/manifests/monolithic/build.go, internal/manifests/monolithic/jaegerui_ingress.go, internal/manifests/monolithic/jaegerui_ingress_test.go
Refactor Jaeger UI ingress/route creation
=> Refactor Jaeger UI ingress/route creation

docs/tempomonolithic.md
Provide a TempoMonolithic doc with examples
=> Provide a TempoMonolithic doc with examples

.github/workflows/e2e.yaml, tests/e2e-upgrade/upgrade/README.md
Fix upgrade test in timeframe between tagging a release and release is published on OperatorHub
=> Fix upgrade test in timeframe between tagging a release and release is published on OperatorHub

.github/workflows/scorecard.yaml
try to fix scorecard tests (again)
=> try to fix scorecard tests (again)

Makefile, RELEASE.md, bundle/community/bundle.Dockerfile, bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/community/metadata/annotations.yaml, bundle/openshift/bundle.Dockerfile, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/metadata/annotations.yaml, config/manifests/community/bases/tempo-operator.clusterserviceversion.yaml, config/manifests/openshift/bases/tempo-operator.clusterserviceversion.yaml
Add minimum Kubernetes and OpenShift versions
Ref. https://github.com/k8s-operatorhub/community-operators/pull/3841#issuecomment-1924433649
Ref. https://docs.openshift.com/container-platform/4.15/operators/operator_sdk/osdk-working-bundle-images.html#osdk-control-compat_osdk-working-bundle-images
=> Add minimum Kubernetes and OpenShift versions

internal/manifests/compactor/compactor.go, internal/manifests/ingester/ingester.go, internal/manifests/manifestutils/storage.go, internal/manifests/manifestutils/storage_test.go, internal/manifests/manifestutils/tls.go, internal/manifests/manifestutils/tls_test.go, internal/manifests/monolithic/statefulset.go, internal/manifests/monolithic/statefulset_test.go, internal/manifests/querier/querier.go, internal/manifests/queryfrontend/query_frontend.go, tests/e2e/custom-ca/01-assert.yaml
Improve TLS handling: search by container name instead of slice index
=> [chore] Improve TLS handling: search by container name instead of slice index

internal/manifests/monolithic/configmap.go
fix apiVersion for tempo monolithic configmap
=> fix apiVersion for tempo monolithic configmap

.chloggen/set_security_context.yaml, internal/manifests/compactor/compactor.go, internal/manifests/compactor/compactor_test.go, internal/manifests/distributor/distributor.go, internal/manifests/distributor/distributor_test.go, internal/manifests/manifestutils/constants.go, internal/manifests/querier/querier.go, internal/manifests/querier/querier_test.go, internal/manifests/queryfrontend/query_frontend.go, internal/manifests/queryfrontend/query_frontend_test.go
Fixes https://github.com/grafana/tempo-operator/issues/864
=> Add security context to query-frontend container

tests/e2e-openshift-object-stores/aws-sts-monolithic/aws-sts-s3-create-assert.yaml, tests/e2e-openshift-object-stores/aws-sts-monolithic/aws-sts-s3-create.sh, tests/e2e-openshift-object-stores/aws-sts-monolithic/aws-sts-s3-delete.sh, tests/e2e-openshift-object-stores/aws-sts-monolithic/chainsaw-test.yaml, tests/e2e-openshift-object-stores/aws-sts-monolithic/generate-traces-assert.yaml, tests/e2e-openshift-object-stores/aws-sts-monolithic/generate-traces.yaml, tests/e2e-openshift-object-stores/aws-sts-monolithic/install-monolithic-assert.yaml, tests/e2e-openshift-object-stores/aws-sts-monolithic/install-monolithic.yaml, tests/e2e-openshift-object-stores/aws-sts-monolithic/verify-traces-assert.yaml, tests/e2e-openshift-object-stores/aws-sts-monolithic/verify-traces.yaml, tests/e2e-openshift-object-stores/aws-sts-tempostack/aws-sts-s3-create-assert.yaml, tests/e2e-openshift-object-stores/aws-sts-tempostack/aws-sts-s3-create.sh, tests/e2e-openshift-object-stores/aws-sts-tempostack/aws-sts-s3-delete.sh, tests/e2e-openshift-object-stores/aws-sts-tempostack/chainsaw-test.yaml, tests/e2e-openshift-object-stores/aws-sts-tempostack/generate-traces-assert.yaml, tests/e2e-openshift-object-stores/aws-sts-tempostack/generate-traces.yaml, tests/e2e-openshift-object-stores/aws-sts-tempostack/install-tempostack-assert.yaml, tests/e2e-openshift-object-stores/aws-sts-tempostack/install-tempostack.yaml, tests/e2e-openshift-object-stores/aws-sts-tempostack/verify-traces-assert.yaml, tests/e2e-openshift-object-stores/aws-sts-tempostack/verify-traces.yaml
Add e2e tests for testing TempoStack and Tempo Monolithic support for AWS STS
```
$ chainsaw test --config .chainsaw-openshift.yaml tests/e2e-openshift-object-stores/
Version: v0.2.6
Loading config (.chainsaw-openshift.yaml)...
- Using test file: chainsaw-test
- TestDirs [tests/e2e-openshift-object-stores/]
- SkipDelete false
- FailFast false
- ReportFormat ''
- ReportName 'chainsaw-report'
- Namespace ''
- FullName false
- IncludeTestRegex ''
- ExcludeTestRegex ''
- ApplyTimeout 10s
- AssertTimeout 5m0s
- CleanupTimeout 5m0s
- DeleteTimeout 5m0s
- ErrorTimeout 5m0s
- ExecTimeout 5m0s
- DeletionPropagationPolicy Background
- NoCluster false
- PauseOnFailure false
Loading tests...
- aws-sts-monolithic (tests/e2e-openshift-object-stores/aws-sts-monolithic)
- aws-sts-tempostack …
```
=> [Chore] Add e2e cases for testing Tempo with AWS STS

internal/manifests/monolithic/build.go, internal/manifests/monolithic/options.go, internal/manifests/monolithic/services.go, internal/manifests/monolithic/services_test.go, internal/manifests/monolithic/util.go
Fix https://issues.redhat.com/browse/TRACING-4474
=> Fix TLS service cert on monolithic

.chloggen/fix_gateway_replicas.yaml, internal/manifests/gateway/gateway.go, internal/manifests/gateway/gateway_test.go, internal/webhooks/tempostack_webhook.go, internal/webhooks/tempostack_webhook_test.go
Fixes https://github.com/grafana/tempo-operator/issues/993
=> Set replicas in gateway component

tests/e2e-openshift/red-metrics/02-install-otel-collector.yaml
```
--- PASS: chainsaw (204.12s)
--- PASS: chainsaw/red-metrics (204.11s)
PASS
- Passed  tests 1
Done.
```
=> [Chore] Remove the collector image from red-metrics test case

.chloggen/fix-annotations-gateway-route.yaml, internal/manifests/gateway/gateway_test.go, internal/manifests/gateway/openshift.go
https://issues.redhat.com/browse/TRACING-4511
=> Fix propagating annotations to Gateway route

.chloggen/bug_1016.yaml, Makefile, internal/manifests/queryfrontend/query_frontend.go, internal/manifests/queryfrontend/query_frontend_test.go, tests/e2e-openshift/red-metrics/02-install-otel-collector.yaml
=> Fix monitoring-view clusterrolebinding when using the oauth proxy 

tests/e2e-openshift/red-metrics/03-assert.yaml
Fix the E2E to assert #1017 properly
=> [Chore] Fix E2E red-metrics test for OpenShift

tests/e2e-openshift/component-replicas/install-tempo-assert.yaml, tests/e2e-openshift/multitenancy/01-assert.yaml
update e2e-openshift tests after default route termination change
default got changed in #1026
=> [chore] update e2e-openshift tests after default route termination change

apis/tempo/v1alpha1/tempostack_types.go, bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/community/manifests/tempo.grafana.com_tempostacks.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo.grafana.com_tempostacks.yaml, config/crd/bases/tempo.grafana.com_tempostacks.yaml, config/manifests/community/bases/tempo-operator.clusterserviceversion.yaml, config/manifests/openshift/bases/tempo-operator.clusterserviceversion.yaml, docs/spec/tempo.grafana.com_tempostacks.yaml
Improve `replicationFactor` documentation.
=> [chore] Improve replication factor documentation

tests/e2e-openshift/component-replicas/scale-tempo-assert.yaml, tests/e2e-openshift/monolithic-route/install-tempo-assert.yaml, tests/e2e-openshift/route/install-tempo-assert.yaml, tests/e2e-openshift/tls-monolithic-singletenant/01-assert.yaml, tests/e2e-openshift/tls-singletenant/01-assert.yaml
The PR fixes the asserts for the tests.
=> [Chore] Fix Tempo e2e tests

tests/e2e-openshift/multitenancy-rbac/00-assert.yaml, tests/e2e-openshift/multitenancy-rbac/00-install-storage.yaml, tests/e2e-openshift/multitenancy-rbac/01-assert.yaml, tests/e2e-openshift/multitenancy-rbac/01-install-tempo.yaml, tests/e2e-openshift/multitenancy-rbac/02-assert.yaml, tests/e2e-openshift/multitenancy-rbac/02-install-otelcol.yaml, tests/e2e-openshift/multitenancy-rbac/03-assert.yaml, tests/e2e-openshift/multitenancy-rbac/03-generate-traces.yaml, tests/e2e-openshift/multitenancy-rbac/04-assert.yaml, tests/e2e-openshift/multitenancy-rbac/04-verify-traces.yaml, tests/e2e-openshift/multitenancy-rbac/chainsaw-test.yaml, tests/e2e-openshift/multitenancy/01-assert.yaml
The PR removes RBAC from tests which has Jaeger Query enabled and adds a separate test.
=> [Chore] Fix tests to enable RBAC without Jaeger Query

go.mod, go.sum
=> Fix x/oauth2/jws CVE-2025-22868

.github/workflows/changelog.yaml, .github/workflows/continuous-integration.yaml
=> [chore] Fix zizmor

.chloggen/watch_secrets_monolitic.yaml, internal/controller/tempo/tempomonolithic_controller.go
I'll address the change of the secret content in a separate PR.
Didn't create an index, because we don't expect too many monolithics in the same namespace.
=> Watch tempo monolithic secrets

tests/e2e-openshift/component-replicas/install-tempo-assert.yaml, tests/e2e-openshift/component-replicas/scale-tempo-assert.yaml, tests/e2e-openshift/multitenancy/01-assert.yaml
Fix asserts after fix PR https://github.com/grafana/tempo-operator/pull/1176
=> [Chore] Fix test asserts

hack/list-components.sh
add supported Kubernetes versions to changelog
=> [chore] add supported Kubernetes versions to changelog

.chloggen/tempo_2.8.yaml, Makefile, bundle/community/manifests/tempo-operator.clusterserviceversion.yaml, bundle/openshift/manifests/tempo-operator.clusterserviceversion.yaml, config/manager/manager.yaml, internal/manifests/config/build.go, internal/manifests/config/build_test.go, internal/manifests/config/options.go, internal/manifests/config/tempo-config.yaml, tests/e2e-openshift/route/install-tempo-assert.yaml, tests/e2e-openshift/tls-singletenant/01-assert.yaml, tests/e2e/tempostack-extraconfig/install-tempostack-assert.yaml
Update Tempo to v2.8.1, and update gateway and opa images
=> Update Tempo to v2.8.1, and update gateway and opa images
